### PR TITLE
[NeurIPS 2023 Streaming Track] Puck

### PR DESCRIPTION
**Pull request by nk2014yj**
Puck participated in the Streaming track. This is the code for Puck. Thank you.

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@nk2014yj  thanks for the PR. Does this agree with your experiments

```
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 160})",text2image-10M,10,8861.585558682262,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9015829999999999
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 165})",text2image-10M,10,8635.750395405932,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9040100000000001
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 170})",text2image-10M,10,8423.64192677345,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9061980000000001
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 175})",text2image-10M,10,8312.184281522512,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9083629999999999
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 190})",text2image-10M,10,7772.49002208958,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9141640000000001
```

**Comment by harsha-simhadri** [comment]
@nk2014yj  please add a CI entry for random-xs

**Comment by nk2014yj** [comment]
I add CI for random-xs of streaming task and merge current master to my branch. But It still has failing checks, It seems to have nothing to do with the streaming subdirectory. Could you give me some hints on how to solve it?

**Comment by maumueller** [comment]
@nk2014yj Don't worry about those. They are failing because the github actions sometimes assigns machines that don't support the necessary CPU instructions.

**Comment by harsha-simhadri** [comment]
@nk2014yj  could you please add an entry here for CI test https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/.github/workflows/neurips23.yml

**Comment by nk2014yj** [comment]
Added CI test of puck （track ood, filter and streaming). Thanks.

**Pull request merged**
