### PR TITLE
ParlayANN submission to filter track

### PR DESCRIPTION
**Pull request by landrumb**
This is the ParlayANN filter submission. We call the algorithm IVF&sup2;, and it's in the framework as `parlayivf`

The parameters are currently less than ideal, and might be updated tomorrow, apologies for not submitting earlier.

Built indices are available to be hosted if the organizers would be interested in hosting them, but build times should be relatively reasonable.

Please let us know if you encounter any issues, and good luck to all participants!

### CODE REVIEW

**Comment by maumueller** [comment]
Thanks. I was able to run your entry and got the following results: Are these in line with your results? 

```
algorithm,parameters,dataset,count,qps,distcomps,build,indexsize,mean_ssd_ios,mean_latency,track,recall/ap
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[40, 40, 40], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,23635.885870951668,0.0,-1,11747132.0,0,0,filter,0.9057280000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[40, 40, 40], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,23165.126606688027,0.0,-1,11747132.0,0,0,filter,0.9058780000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[50, 50, 50], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,22757.41373196976,0.0,-1,11747132.0,0,0,filter,0.9200419999999999
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[50, 50, 50], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,23378.14451294687,0.0,-1,11747132.0,0,0,filter,0.9201919999999999
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[60, 60, 60], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,22271.90291386071,0.0,-1,11747132.0,0,0,filter,0.9297610000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[60, 60, 60], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,22218.94724574419,0.0,-1,11747132.0,0,0,filter,0.929911
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[70, 70, 70], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,20671.234149321346,0.0,-1,11747132.0,0,0,filter,0.937422
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[70, 70, 70], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,20856.96313000843,0.0,-1,11747132.0,0,0,filter,0.937572
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[90, 90, 90], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,21312.852797043124,0.0,-1,11747132.0,0,0,filter,0.9483050000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[90, 90, 90], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,21270.13568896451,0.0,-1,11747132.0,0,0,filter,0.948455
```

**Comment by maumueller** [comment]
I did the evaluation on the public query workload (just to make sure that it works on the evaluation machine), so I wouldn't suggest submitting a new set of parameters. (Technically, the deadline has passed as well :-))

**Comment by landrumb** [comment]
Whoops, my bad, thought the deadline was the end of the month! I won't push my changes, consider this submission camera-ready.

**Comment by maumueller** [comment]
@landrumb I didn't see Harsha's comment on #196. You can still submit changes until Oct 31, AoE.

**Comment by maumueller** [comment]
I'm seeing the following results with these new settings:

```
algorithm,parameters,dataset,count,qps,distcomps,build,indexsize,mean_ssd_ios,mean_latency,track,recall/ap
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=5,000, tiny_cutoff=28,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[90, 57, 90], search_limits=[500, 500, 500])",yfcc-10M,10,32218.102434464265,0.0,-1,10171996.0,0,0,filter,0.9032120000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=5,000, tiny_cutoff=30,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[85, 50, 95], search_limits=[500, 500, 500])",yfcc-10M,10,31846.849774552185,0.0,-1,10171996.0,0,0,filter,0.903306
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=7,500, tiny_cutoff=35,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[55, 55, 55], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,29435.61268516985,0.0,-1,10171996.0,0,0,filter,0.9043720000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[40, 40, 40], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,25698.499411991837,0.0,-1,10171996.0,0,0,filter,0.9057280000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[40, 40, 40], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,25000.47386590775,0.0,-1,10171996.0,0,0,filter,0.9058780000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[50, 50, 50], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,24972.18369431023,0.0,-1,10171996.0,0,0,filter,0.9200419999999999
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[50, 50, 50], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,25113.720563945983,0.0,-1,10171996.0,0,0,filter,0.9201919999999999
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[60, 60, 60], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,24937.126609350707,0.0,-1,10171996.0,0,0,filter,0.929911
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=60,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[90, 90, 90], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,23235.15116101413,0.0,-1,10171996.0,0,0,filter,0.9483050000000001
parlayivf,"ParlayIVF(metric=Euclidian, dtype=uint8, T=8, cluster_size=5,000, cutoff=10,000, target_points=15,000, tiny_cutoff=100,000, max_iter=10, weight_classes=(100000, 400000), max_degrees=(8, 10, 12), beam_widths=[90, 90, 90], search_limits=[100000, 400000, 3000000])",yfcc-10M,10,23166.715741857537,0.0,-1,10171996.0,0,0,filter,0.948455
```

Is this ready to be merged?

**Comment by landrumb** [comment]
@maumueller Yes, ready to merge, thanks for running again.

**Comment by mdouze** [comment]
@landrumb Would you mind explaining how the method works? 
I skimmed through https://github.com/cmuparlay/ParlayANN/compare/main...filter
My understanding is that you construct an inverted index for all pairs of 2 terms (term1, term2) that occur sufficiently often. Is that correct?

**Pull request merged**
