### PR TITLE
add NGT to T1 and T2

### PR DESCRIPTION
**Pull request by masajiro**
I have not got results with this parameter setting yet, and our method might not surpass the baselines.

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
> I have added random-xs tests.

Thanks. Could you please add URL to pre-built indices to your PR?

**Comment by masajiro** [comment]
@harsha-simhadri 
We don't have indices with the same parameters as our PR, and unfortunately spent almost all of our budget to use azure VMs. We are currently focusing on improving our search algorithm,  and are going to release it in a few days.

**Comment by masajiro** [comment]
I added prebuilt indices that were built on our in house servers, and rebuilding the docker NGT image is also necessary. However, these indices might be updated because we are going to tune some parameters continuously.

**Comment by masajiro** [comment]
@harsha-simhadri 
Although our results do not definitely surpass the results of the winner, did you try to run this PR?

**Pull request merged**
