### PR TITLE
add public query results on plots for Azure D8lds v5 

### PR DESCRIPTION
**Pull request by harsha-simhadri**

### CODE REVIEW

**Comment by SDU-L** [comment]
@harsha-simhadri  Hi, harsha-simhadri, May I ask why there is no DHQ algorithm result in the neurips23/filter/plot_public_queries_AzureD8lds_v5.png you just updated? Thank you very much.

**Comment by harsha-simhadri** [comment]
> @harsha-simhadri Hi, harsha-simhadri, May I ask why there is no DHQ algorithm result in the neurips23/filter/plot_public_queries_AzureD8lds_v5.png you just updated? Thank you very much.

@SDU-L  Thanks for pointing this out. This PR is still in draft mode. I have not completed all the runs. I am still uploading data. I will change the status from draft PR to PR when all runs complete.

**Comment by harsha-simhadri** [comment]
@SDU-L  I added the DHQ plot. Does it look OK to you?

**Comment by masajiro** [comment]
@harsha-simhadri 
There is no entry of NGT in the [figure](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/harshasi/results_public_query_azure/neurips23/ood/plot_public_queries_AzureD8lds_v5.png). Is there  any reason for this?

**Review by ingberam — CHANGES_REQUESTED** [review]
I reviewed the sparse track.

1. `sustech-whu` is missing in both the plot and results file. While @maumueller reports that the build time took more than the 12 hours (about 14), I think we should still include it (with an asterisk). 

2. please remove NLE-Full from the plot and results file. It is a repeated submission from the nle team and has a lot more than 10 hyperparamer sets, so I assume it is not intended for submission.

3. results file:`shnsw` is missing. can you add it?  (it does appear in the plot).

```
$ cat res_public_queries_AzureD8lds_v5.csv | cut -d',' -f1 | uniq -c
      1 algorithm
    125 NLE-Full
     10 cufe
     10 linscan
     10 nle
     10 pyanns
```

**Comment by harsha-simhadri** [comment]
> @harsha-simhadri There is no entry of NGT in the [figure](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/harshasi/results_public_query_azure/neurips23/ood/plot_public_queries_AzureD8lds_v5.png). Is there any reason for this?

Its on oversight. Will look into this. I could not run your entry on all machines. This must be from one of those machines where it failed.

**Comment by masajiro** [comment]
> Its on oversight. Will look into this. I could not run your entry on all machines. This must be from one of those machines where it failed.

Did you run [this last commit](https://github.com/harsha-simhadri/big-ann-benchmarks/pull/187#issuecomment-1785891143)? Since NGT was updated after our submission before the deadline, you should rebuild it and avoid using the cache of NGT source code.

**Comment by masajiro** [comment]
> Update: failed on 2 more machines. Onto a third. Will update.

In addition, I would like you to confirm the following messages in the build log. In particular, the commit number of NGT source must be the same as that in your server's log.

```
Step 6/11 : RUN cd NGT && git log -n 1
 ---> Running in adc04f274b08
commit 39c584f6f5c69d9afc373bbba27552296235320f
Author: Masajiro Iwasaki <masajiro.iwasaki@gmail.com>
Date:   Mon Oct 30 18:45:37 2023 +0000
```

**Comment by matchyc** [comment]
Hello @harsha-simhadri,

I've noticed that the PR is now open, and I just have some concerns because I observed that the plot has been updated in this [1afc681d8df](https://github.com/harsha-simhadri/big-ann-benchmarks/pull/233/commits/1afc681d8df08c3604d2736dd2a67a5d32c6168f) since the last time I viewed it a few days ago in the [1cb63a847](https://github.com/harsha-simhadri/big-ann-benchmarks/pull/233/commits/1cb63a8470c4fbf4ced2a6bbafaf1c5d52081bcd).

It appears that three algorithms (namely puck, puck-fizz, and vamana) have been added to the figure. However, when comparing the two plots, it shows that all the algorithms present in [the previous commit](https://github.com/harsha-simhadri/big-ann-benchmarks/pull/233/commits/1afc681d8df08c3604d2736dd2a67a5d32c6168f) maintain the same performance at the pixel-level, except for `pyanns`. In this instance, the curve has shifted by 20% (approximately to 1/5 grid box) when comparing the two plots, while the performance of the others remains unchanged. Is there any reason for this? Thanks.

**Comment by SDU-L** [comment]
> @SDU-L I added the DHQ plot. Does it look OK to you?

@harsha-simhadri  That’s ok.Thank you very much.

**Comment by ingberam** [comment]
@harsha-simhadri on the filter track, there are two entries that seem duplicates: `mysteryann` and `mysteryann-dif`. is this intentional?

**Comment by harsha-simhadri** [comment]
> @harsha-simhadri on the filter track, there are two entries that seem duplicates: `mysteryann` and `mysteryann-dif`. is this intentional?

I thought these were two submissions from the same team. As the organizer in charge of the track, please decide whether to accept two submission or only on.

**Comment by harsha-simhadri** [comment]
> > Update: failed on 2 more machines. Onto a third. Will update.
> 
> In addition, I would like you to confirm the following messages in the build log. In particular, the commit number of NGT source must be the same as that in your server's log.
> 
> ```
> Step 6/11 : RUN cd NGT && git log -n 1
>  ---> Running in adc04f274b08
> commit 39c584f6f5c69d9afc373bbba27552296235320f
> Author: Masajiro Iwasaki <masajiro.iwasaki@gmail.com>
> Date:   Mon Oct 30 18:45:37 2023 +0000
> ```

Yes, this is the commit I cloned and ran on the extra machines. It failed again. I am trying one more time.

**Comment by masajiro** [comment]
@harsha-simhadri 
I use `Linux (ubuntu 22.04)` with Azure Standard D8lds v5. On the instance, building the NGT index never fails. I think there is definitely something different between my azure server and your azure server. Another try will also fail. Which instance do you use?

**Comment by ingberam** [comment]
> > @harsha-simhadri on the filter track, there are two entries that seem duplicates: `mysteryann` and `mysteryann-dif`. is this intentional?
> 
> I thought these were two submissions from the same team. As the organizer in charge of the track, please decide whether to accept two submission or only on.

@harsha-simhadri I meant the OOD track (not the filter track), I believe this is your track.
There are actually two pairs of submissions that look like duplicates: {`mysteryann` and `mysteryann-dif`} and {`puck` and `puck-fizz`}. 
Another issue is that some submissions have more than 10 sets of hyperparameters, where most submissions did adhere to that rule. We don't want this to end up being the deciding factor as to who is the winner of a track.

Also, the csv results file for the ood track seems like the wrong file (it is some binary file and not csv).

**Comment by maumueller** [comment]
>>> @harsha-simhadri on the filter track, there are two entries that seem duplicates: mysteryann and mysteryann-dif. is this intentional?

>> I thought these were two submissions from the same team. As the organizer in charge of the track, please decide whether to accept two submission or only on.

> @harsha-simhadri I meant the OOD track (not the filter track), I believe this is your track.
> There are actually two pairs of submissions that look like duplicates: {mysteryann and mysteryann-dif} and {puck and puck-fizz}.

I believe both teams take the public query set for text2image into account for their second solution (`-dif` and `-fizz`).

> Another issue is that some submissions have more than 10 sets of hyperparameters, where most submissions did adhere to > that rule. We don't want this to end up being the deciding factor as to who is the winner of a track.

I checked for this for the ones that I merged, do you have a list of offending submissions? I will check one more time otherwise.

**Comment by ingberam** [comment]
List of the offending submissions:

'neurips23/ood/mysteryann-dif/config.yaml':
text2image-10M.mysteryann-dif: 'query-args' count = 14
'neurips23/ood/mysteryann/config.yaml':
text2image-10M.mysteryann: 'query-args' count = 16
'neurips23/ood/pyanns/config.yaml':
text2image-10M.pyanns: 'query-args' count = 12
'neurips23/sparse/nle/config.yaml':
sparse-small.NLE-Full: 'query-args' count = 25
'neurips23/sparse/nle/config.yaml':
sparse-1M.NLE-Full: 'query-args' count = 25
'neurips23/sparse/nle/config.yaml':
sparse-full.NLE-Full: 'query-args' count = 25
'neurips23/sparse/shnsw/config.yaml':
sparse-full.shnsw: 'query-args' count = 13
'neurips23/filter/faiss/config.yaml':
yfcc-10M.faiss: 'query-args' count = 18
'neurips23/filter/puck/config.yaml':
yfcc-10M.puck: 'query-args' count = 12

**Comment by nk2014yj** [comment]
> > > @harsha-simhadri on the filter track, there are two entries that seem duplicates: `mysteryann` and `mysteryann-dif`. is this intentional?
> > 
> > 
> > I thought these were two submissions from the same team. As the organizer in charge of the track, please decide whether to accept two submission or only on.
> 
> @harsha-simhadri I meant the OOD track (not the filter track), I believe this is your track. There are actually two pairs of submissions that look like duplicates: {`mysteryann` and `mysteryann-dif`} and {`puck` and `puck-fizz`}. Another issue is that some submissions have more than 10 sets of hyperparameters, where most submissions did adhere to that rule. We don't want this to end up being the deciding factor as to who is the winner of a track.
> 
> Also, the csv results file for the ood track seems like the wrong file (it is some binary file and not csv).

puck-fizz could be removed from the results, as it misunderstood the concept of query train datasets. I'm sorry for the mistake.

**Comment by harsha-simhadri** [comment]
> > > > @harsha-simhadri on the filter track, there are two entries that seem duplicates: `mysteryann` and `mysteryann-dif`. is this intentional?
> > > 
> > > 
> > > I thought these were two submissions from the same team. As the organizer in charge of the track, please decide whether to accept two submission or only on.
> > 
> > 
> > @harsha-simhadri I meant the OOD track (not the filter track), I believe this is your track. There are actually two pairs of submissions that look like duplicates: {`mysteryann` and `mysteryann-dif`} and {`puck` and `puck-fizz`}. Another issue is that some submissions have more than 10 sets of hyperparameters, where most submissions did adhere to that rule. We don't want this to end up being the deciding factor as to who is the winner of a track.
> > Also, the csv results file for the ood track seems like the wrong file (it is some binary file and not csv).
> 
> puck-fizz could be removed from the results, as it misunderstood the concept of query train datasets. I'm sorry for the mistake.

removed

**Comment by harsha-simhadri** [comment]
> @harsha-simhadri I use `Linux (ubuntu 22.04)` with Azure Standard D8lds v5. On the instance, building the NGT index never fails. I think there is definitely something different between my azure server and your azure server. Another try will also fail. Which instance do you use?

I use the same image on the same machine. I had to remove every other entry, prune down a lot of other stuff to run your entry. I added it to the plot. In the future, I would request that an entry not push the DRAM requirement so far to the limit as some natural variation on a machineis to be expected when running all entries. Thanks for your patience.

**Pull request merged**
