### PR TITLE
[Neurips23] NLE submission for the sparse track

### PR DESCRIPTION
**Pull request by cadurosar**
Hi, this is our NLE submission for the sparse track. We have added two configs (changed the names after the figure, nle is NLE-10 and NLE-FULL is NLE), nle (the official one, with the 10 configurations for the end competition) and a NLE-Full with more configs to test different configurations. nle takes around 12 hours to run completely (sparse-small, sparse-1M and sparse-full) and indexing could be made much faster, this was just the first one we got to work.

For running nle quicker, we make all the indexes available [here](https://www.dropbox.com/scl/fi/4b80qv9pt50za608tfep5/indexes.zip?rlkey=hy2xryqa1ts2xx54ss5y9fyoe&dl=0), just need to extract in big-ann-benchmarks/results/indexes

We have tested our solution on three machines:

Azure (Standard D4s v5 (4 vcpus, 16 GiB memory)

azure-sparse-full

Mac M1 (16G, linscan could not run due to lack of memory, I never got the machine to be with more than 11G free...)

sparse-full

Internal server (64 CPU - Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz, linscan does not work right a lot of threads, while our method is bottlenecked by 200ms to preprocess query data)

sparse-full

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
Thanks for the submission. could you please run.sh (perhaps add it as comments in the PR instead) and add a CI test for your algorithm and sparse-small dataset in .github/neurips23.yaml?

**Comment by cadurosar** [comment]
Hi @harsha-simhadri, from what I understood I removed the run.sh and added to the workflow, but I'm not sure how to test if the adding to the workflow worked.

**Comment by harsha-simhadri** [comment]
I see the CI test for NLE is green. Thanks for that.
I am running NLE on sparse-full on the competition spec VM. Will merge once that completes.

**Comment by harsha-simhadri** [comment]
These are the results I see on the competition spec VM

nle,pisa,sparse-full,10,2993.964456425476,0.0,1000000.0,10371632.0,3464.1800699206683,0,0,sparse,0.8624498567335243
nle,pisa,sparse-full,10,3001.2004210420996,0.0,1000000.0,10371632.0,3455.827850510125,0,0,sparse,0.8634527220630372
nle,pisa,sparse-full,10,2836.924317267769,0.0,1000000.0,10371632.0,3655.942436275099,0,0,sparse,0.8725787965616046
nle,pisa,sparse-full,10,2567.266042978288,0.0,1000000.0,10371632.0,4039.95216170423,0,0,sparse,0.8923065902578797
nle,pisa,sparse-full,10,2455.7393810658486,0.0,1000000.0,10371632.0,4223.425368329789,0,0,sparse,0.8980085959885387
nle,pisa,sparse-full,10,2365.8710581835744,0.0,1000000.0,10371632.0,4383.853449715448,0,0,sparse,0.902349570200573
nle,pisa,sparse-full,10,2275.55007253081,0.0,1000000.0,10371632.0,4557.8570760541115,0,0,sparse,0.9059455587392551
nle,pisa,sparse-full,10,2208.434808525321,0.0,1000000.0,10371632.0,4696.372272326953,0,0,sparse,0.9083810888252148
nle,pisa,sparse-full,10,2087.793570011214,0.0,1000000.0,10371632.0,4967.7478410589665,0,0,sparse,0.9110171919770774
nle,pisa,sparse-full,10,1700.6021543377224,0.0,1000000.0,10371632.0,6098.799753690244,0,0,sparse,0.9195845272206304

Does this agree with your observations? IF so, I can merge this PR

**Comment by cadurosar** [comment]
Hi harsha, the numbers are smaller than what I had expected and I found a bug on the number of threads (it was hardcoded to 4 threads instead of CPU count), could you please run the new version?

**Comment by cadurosar** [comment]
Hi @harsha-simhadri, sorry for this, the result seem weird because there was no difference between 4 hard-coded threads and what was supposed to be 8. I've hardcoded it to 8 now and if there's no difference I probably had hardcoded somewhere to 8 before and I'm not finding (code is not as clean as it could be as you're seeing). Can you please try with the newest commit and if there's no difference I think I will just leave as is.

**Comment by harsha-simhadri** [comment]
@cadurosar  Let me merge this to make way for other submissions. Feel free to investigate further and submit any config changes before Oct 31 deadline.

**Review by harsha-simhadri — APPROVED** [review]

**Pull request merged**
