### PR TITLE
[NeurIPS 2023 Filter Track] hwtl_sdu_anns_filter

### PR DESCRIPTION
**Pull request by KhylonWong**
Here is the code for team HWTL_SDU-ANNS. Thank you.

### CODE REVIEW

**Comment by maumueller** [comment]
This worked well and I got the following results. 

```
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 4, 3, 3000)",yfcc-10M,10,23909.896891055105,0.0,5529.82418680191,9116888.0,0,0,filter,0.830894
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 4, 4, 3000)",yfcc-10M,10,23686.46899818976,0.0,5529.82418680191,9116888.0,0,0,filter,0.845252
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 8, 3, 3000)",yfcc-10M,10,15885.007245825735,0.0,5529.82418680191,9116888.0,0,0,filter,0.883726
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 8, 4, 3000)",yfcc-10M,10,15808.460275227431,0.0,5529.82418680191,9116888.0,0,0,filter,0.9028750000000001
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 12, 3, 3000)",yfcc-10M,10,12465.124921129029,0.0,5529.82418680191,9116888.0,0,0,filter,0.902992
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 16, 3, 3000)",yfcc-10M,10,10611.742876726064,0.0,5529.82418680191,9116888.0,0,0,filter,0.9123430000000001
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 32, 3, 3000)",yfcc-10M,10,7564.692551262137,0.0,5529.82418680191,9116888.0,0,0,filter,0.924512
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 12, 4, 3000)",yfcc-10M,10,12420.693887415251,0.0,5529.82418680191,9116888.0,0,0,filter,0.92455
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 16, 4, 3000)",yfcc-10M,10,10593.899881515541,0.0,5529.82418680191,9116888.0,0,0,filter,0.9350310000000001
hwtl_sdu_anns_filter,"HWTL_SDU-ANNS-filter(gffc, 32, 4, 3000)",yfcc-10M,10,7551.848260119234,0.0,5529.82418680191,9116888.0,0,0,filter,0.9489420000000001
```

Merging this, thanks for your contribution.

**Comment by WPJiang** [comment]
@maumueller ,  we forgot to change the informaiton in NeurIPS 2023 Competition track,  our register information in the  Competition system is below, which seems no relevance with our team name "HWTL_SDU-ANNS" .Sorry for the inconvenience.

**Conference Name**:Practical Vector Search Challenge: NeurIPS 2023 Competition track
**Paper ID** 30
**Paper Title** A graph-based algorithm for K-Nearest Neighbor search.

I want to change the paper title to "HWTL_SDU-ANNS" this morning, but it can not be changed anymore.  So I added the team  information  in the Supplementary Files "[hwtl_sdu_anns_streaming and hwtl_sdu_anns_filter.pdf]".  Please use the **Paper ID** and **Paper Title**  to find our register information, thank you!

**Comment by maumueller** [comment]
Thank you @WPJiang. We will make sure to connect your submission to the correct CMT entry.

**Comment by mdouze** [comment]
Hi HWTL_SDU team,
I am preparing a few summary slides for the bigann challenge for the neurips track on Sat 16th.
Would you mind summarizing how your indexing works? The submission nb 30 PDF does not contain too much detail. Thanks!

**Comment by WPJiang** [comment]
> Hi HWTL_SDU team, I am preparing a few summary slides for the bigann challenge for the neurips track on Sat 16th. Would you mind summarizing how your indexing works? The submission nb 30 PDF does not contain too much detail. Thanks!
For filter track:
1. We create a separate index for each tag. Such an index is used for queries containing the corresponding tag (including single and double tag queries).

2. We optimize the probability for 1s in a random signature by minimizing the probability Pr[the signature of a vector with 10 tags other than t covers the signature of t] for a fixed tag t.

**Comment by WPJiang** [comment]
> Hi HWTL_SDU team, I am preparing a few summary slides for the bigann challenge for the neurips track on Sat 16th. Would you mind summarizing how your indexing works? The submission nb 30 PDF does not contain too much detail. Thanks!

Hi, @mdouze ，we find that in the ”summary.pdf”， The team members of Track-stream hwtl_sdu_anns_stream are mistakenly thought to be the same as Track-filter hwtl_sdu_anns_filter.  In fact, the team members of hwtl_sdu_anns_stream are different， and should be

HWTL: Weipeng Jiang, Yu Gao, Weixi Zhang, Chengda Wu, Chaorui Zhang, Yibin Ding, Wei Han, Bo Bai
SDU：Kun Wang, Yansong MU, Yupeng Hu, Liqiang Nie

Can you please change  page 17 of the ”summary.pdf” file on the website (https://big-ann-benchmarks.com/neurips23.html) ?

**Pull request merged**
