### PR TITLE
pinecone's streaming algorithm

### PR DESCRIPTION
**Pull request by ingberam**
pinecone's streaming algorithm. Expected results on the standard Azure VM:
```
pinecone,"pinecone(('R32_L100', {'Ls': 500, 'k_1': 30, 'T': 8}))",msturing-30M-clustered(final_runbook.yaml),10,,0.0,0.4697451591491699,2010972.0,0.0,0.0,streaming,0.997470000000012
````

streaming

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
All four pinecone submissions have a different naming convention. Do you want to make it unform before I merge?

**Comment by harsha-simhadri** [comment]
Is this the commandline?
```python run.py --algorithm pinecone --neurips23track streaming --dataset msturing-30M-clustered```

**Comment by ingberam** [comment]
> @ingberam All four pinecone submissions have a different naming convention. Do you want to make it unform before I merge?

That's fine. all names are wither pinecone or pinecone-xxx. Let's just merge.

**Comment by ingberam** [comment]
> Is this the commandline? `python run.py --algorithm pinecone --neurips23track streaming --dataset msturing-30M-clustered`

@harsha-simhadri  actually this is not the right commandline (it fails for all algorithms).

This is the correct command (note the explicit runbook path):

```
python run.py --dataset msturing-30M-clustered --algorithm pinecone --neurips23track streaming --runbook_path neurips23/streaming/final_runbook.yaml 
```

**Comment by harsha-simhadri** [comment]
Only one entry ran to completion. The other two did not complete.

pinecone,"pinecone(('R32_L100', {'Ls': 300, 'k_1': 30, 'T': 8}))",msturing-30M-clustered(final_runbook.yaml),10,,0.0,0.4844532012939453,2012204.0,0.0,0.0,streaming,0.9908199999999938

**Pull request merged**
