### PR TITLE
Streaming/cufe

### PR DESCRIPTION
**Pull request by ZiaddAhmedd**
Submitting the streaming track for the contest
**Team name: cufe**

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@ZiaddAhmedd  Could you please add a CI test entry for your algo

**Comment by ZiaddAhmedd** [comment]
I have added a CI test workflow cufe_CI.yml and removed the other workflows

**Comment by ZiaddAhmedd** [comment]
Is there still a problem with our files?

**Comment by AbdelrahmanMohamed129** [comment]
is there any problem considering the merge of this branch?

**Comment by harsha-simhadri** [comment]
@AbdelrahmanMohamed129  I see the following results. Are they as you expected

```
cufe,"diskann(('R32_L50', {'Ls': 70, 'T': 16}))",msturing-30M-clustered(final_runbook.yaml),10,,0.0,1.7107985019683838,4885612.0,0.0,0.0,streaming,0.7688699999999955
cufe,"diskann(('R32_L70', {'Ls': 70, 'T': 16}))",msturing-30M-clustered(final_runbook.yaml),10,,0.0,1.7178819179534912,4885448.0,0.0,0.0,streaming,0.7937900000000012
cufe,"diskann(('R50_L50', {'Ls': 70, 'T': 16}))",msturing-30M-clustered(final_runbook.yaml),10,,0.0,1.9073610305786133,4885652.0,0.0,0.0,streaming,0.8189199999999953
```

**Comment by AbdelrahmanMohamed129** [comment]
yes these are the results thanks

**Comment by harsha-simhadri** [comment]
@AbdelrahmanMohamed129  thanks. Could you please remove the CI testfile specifically for cufe (or move it to your algo folder for reference). once that is done, I will merge.

**Comment by AbdelrahmanMohamed129** [comment]
i just deleted it

**Pull request merged**
