### PR TITLE
T3: NVIDIA Single GPU (cuanns_ivfpq)

### PR DESCRIPTION
**Pull request by anaruse**
This is a submission of the NVIDIA team for single GPU in T3 track.
After the built index upload is complete, we will update instructions on how to download the index files.

### CODE REVIEW

**Comment by sourcesync** [comment]
@anaruse.  OK, we synced over the new config and re-ran the evaluation.  Please verify the following:

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/t3/cuanns_ivfpq/algos.yaml

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/t3/eval_2021/cuanns_ivfpq/EvalPublic.ipynb

**Comment by sourcesync** [comment]
@anaruse OK, we synced your new algos yaml and reran.  It looks like a slight improvement to text2image-1B.  Please verify the config and results notebook below:

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/t3/cuanns_ivfpq/algos.yaml

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/t3/eval_2021/cuanns_ivfpq/EvalPublic.ipynb

**Comment by anaruse** [comment]
Thank you for re-running it. I've checked the config and the results. It looks good to me!

**Comment by sourcesync** [comment]
@anaruse Great.

**Comment by sourcesync** [comment]
@anaruse  OK, we re-evaluated your submission.  The "anomaly" count was reduced successfully from 7 to 5.  Thanks.

Can you verify the following?

new config we synced:  

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/t3/cuanns_ivfpq/algos.yaml

eval notebook -  https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/t3/eval_2021/cuanns_ivfpq/EvalPublic.ipynb

Thanks!

**Review by sourcesync — APPROVED** [review]
LGTM

**Pull request merged**
