### PR TITLE
[NeurIPS 2023 Filter Track] FduFilterDiskANN

### PR DESCRIPTION
**Pull request by PUITAR**

### CODE REVIEW

**Comment by maumueller** [comment]
Thanks @PUITAR! 

Please: 
1. do not remove/change files outside your submission (`neurips23/filter/faiss` and `neurips23/filter/wm_filter`) 
2. merge/rebase with main to avoid the conflict on `.github/worksflows/neurips23.yml`.

Let me know when you have updated your submission.

**Review by maumueller — CHANGES_REQUESTED** [review]
The CI run complains https://github.com/harsha-simhadri/big-ann-benchmarks/actions/runs/6705826548/job/18221049916?pr=223#step:5:48.

**Comment by maumueller** [comment]
I have fixed the encoding problem and I'm getting the following results:

```csv
algorithm,parameters,dataset,count,qps,distcomps,build,indexsize,mean_ssd_ios,mean_latency,track,recall/ap
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 10, 'T': 16, 'threshold_1': 15000, 'threshold_2': 40000}))",yfcc-10M,10,3390.6792198287617,0.0,2875.61852145195,10237072.0,0,0,filter,0.877464
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 10, 'T': 16, 'threshold_1': 20000, 'threshold_2': 30000}))",yfcc-10M,10,4384.469399008496,0.0,2875.61852145195,10237072.0,0,0,filter,0.886187
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 10, 'T': 16, 'threshold_1': 20000, 'threshold_2': 40000}))",yfcc-10M,10,3743.449360339158,0.0,2875.61852145195,10237072.0,0,0,filter,0.8986280000000001
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 12, 'T': 16, 'threshold_1': 20000, 'threshold_2': 40000}))",yfcc-10M,10,3761.1307367008158,0.0,2875.61852145195,10237072.0,0,0,filter,0.8989269999999999
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 15, 'T': 16, 'threshold_1': 20000, 'threshold_2': 40000}))",yfcc-10M,10,3751.1565115817775,0.0,2875.61852145195,10237072.0,0,0,filter,0.89924
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 20, 'T': 16, 'threshold_1': 20000, 'threshold_2': 40000}))",yfcc-10M,10,3720.9039239180156,0.0,2875.61852145195,10237072.0,0,0,filter,0.899697
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 50, 'T': 16, 'threshold_1': 20000, 'threshold_2': 40000}))",yfcc-10M,10,3478.0535469976026,0.0,2875.61852145195,10237072.0,0,0,filter,0.902143
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 100, 'T': 16, 'threshold_1': 20000, 'threshold_2': 40000}))",yfcc-10M,10,3544.7197197869746,0.0,2875.61852145195,10237072.0,0,0,filter,0.906794
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 10, 'T': 16, 'threshold_1': 20000, 'threshold_2': 50000}))",yfcc-10M,10,3343.2430641562255,0.0,2875.61852145195,10237072.0,0,0,filter,0.907192
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 10, 'T': 16, 'threshold_1': 30000, 'threshold_2': 40000}))",yfcc-10M,10,4395.340040683815,0.0,2875.61852145195,10237072.0,0,0,filter,0.929476
```

Are these in line with your results?

**Comment by maumueller** [comment]
@PUITAR it was easy to fix the encoding in the web editor, so I did it in [1aaec6f](https://github.com/harsha-simhadri/big-ann-benchmarks/pull/223/commits/1aaec6fca58e6a6df0ac6d6b26f77601af912285)

**Comment by PUITAR** [comment]
This algorithm's CI test was almost finished, but the case of faiss and the case of wm_filter are failed, please check again. orz

**Comment by maumueller** [comment]
This looks much better, thanks. I got the following results on the public query load:

```
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 11, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41000}))",yfcc-10M,10,4609.955421313067,0.0,2563.1165935993195,10159116.0,0,0,filter,0.9643560000000001
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 11, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41100}))",yfcc-10M,10,4603.296893829524,0.0,2563.1165935993195,10159116.0,0,0,filter,0.964363
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 11, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41200}))",yfcc-10M,10,4604.163504323714,0.0,2563.1165935993195,10159116.0,0,0,filter,0.964374
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 11, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41300}))",yfcc-10M,10,4617.161723764712,0.0,2563.1165935993195,10159116.0,0,0,filter,0.964381
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 11, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41400}))",yfcc-10M,10,4616.1412006283135,0.0,2563.1165935993195,10159116.0,0,0,filter,0.9643840000000001
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 12, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41000}))",yfcc-10M,10,4616.736954896197,0.0,2563.1165935993195,10159116.0,0,0,filter,0.964457
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 12, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41200}))",yfcc-10M,10,4616.0395947811585,0.0,2563.1165935993195,10159116.0,0,0,filter,0.964475
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 12, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41300}))",yfcc-10M,10,4614.08485820132,0.0,2563.1165935993195,10159116.0,0,0,filter,0.964482
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 12, 'T': 16, 'threshold_1': 53500, 'threshold_2': 41400}))",yfcc-10M,10,4613.293410669581,0.0,2563.1165935993195,10159116.0,0,0,filter,0.964485
fdufilterdiskann,"diskann(('R60_L80', {'Ls': 12, 'T': 16, 'threshold_1': 53500, 'threshold_2': 51100}))",yfcc-10M,10,4584.895713152285,0.0,2563.1165935993195,10159116.0,0,0,filter,0.9651289999999999
```

Is this ready to be merged?

**Review by maumueller — APPROVED** [review]

**Comment by PUITAR** [comment]
I have just modified my configure file, it might work better... orz
Thank you very much for your patience. 😊

**Comment by PUITAR** [comment]
We are ready to merge, so please : )

**Comment by mdouze** [comment]
Hi @PUITAR 
I am preparing a few summary slides for the bigann challenge for the neurips track on Sat 16th.
Would you mind summarizing how your indexing works? Or otherwise send me slides, any info is welcome.
Also please include the list of authors + affiliations.
Thanks!

**Pull request merged**
