### PR TITLE
a proposed recall-with-ties impl with related unit tests

### PR DESCRIPTION
**Pull request by sourcesync**
@harsha-simhadri @maumueller @

Per our discussion, here is a new recall-with-ties approach with a bunch of recall related unit tests.  

Please review if you get a chance, since it is fairly different from the existing implementation and could really use a second pair of eyes.

Highlights include:
* retains the set intersection method to determine number of recalls, but changes how the true_ids set is presented to it
* basically it groups ids in true_ids by grouping "close" values in true_dists
* "close"ness is determined by the absolute value difference of consecutive distances in true_dists ( treshold is <= 1e-6 )
* it uses the first element in a consecutive group as one of the subtraction operands
* it will also track the tie condition and surfaces the count of queries in query set with the tie condition
* recall_tests.py attempts to provide a comprehensive set of unit tests for both versions of recall (without and with ties)
* there is a run script for these tests ( tests/tests.sh ) which could be incorporated into a github action

Lowlights include:
* admittedly this recall-with-ties implementation could be faster using vectorization
* there are some slow tests in recall_tests.py which may slow down github push validation further if incorporated as-is as a branch push action

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
> @harsha-simhadri @maumueller @
> 
> Per our discussion, here is a new recall-with-ties approach with a bunch of recall related unit tests.
> 
> Please review if you get a chance, since it is fairly different from the existing implementation and could really use a second pair of eyes.
> 
> Highlights include:
> 
> * retains the set intersection method to determine number of recalls, but changes how the true_ids set is presented to it
> * basically it groups ids in true_ids by grouping "close" values in true_dists
> * "close"ness is determined by the absolute value difference of consecutive distances in true_dists ( treshold is <= 1e-6 )
> * it uses the first element in a consecutive group as one of the subtraction operands
> * it will also track the tie condition and surfaces the count of queries in query set with the tie condition
> * recall_tests.py attempts to provide a comprehensive set of unit tests for both versions of recall (without and with ties)
> * there is a run script for these tests ( tests/tests.sh ) which could be incorporated into a github action
> 
> Lowlights include:
> 
> * admittedly this recall-with-ties implementation could be faster using vectorization
> * there are some slow tests in recall_tests.py which may slow down github push validation further if incorporated as-is as a branch push action

@sourcesync  does this PR handle max inner product metric as well?

**Comment by sourcesync** [comment]
> > @harsha-simhadri @maumueller @
> > Per our discussion, here is a new recall-with-ties approach with a bunch of recall related unit tests.
> > Please review if you get a chance, since it is fairly different from the existing implementation and could really use a second pair of eyes.
> > Highlights include:
> > 
> > * retains the set intersection method to determine number of recalls, but changes how the true_ids set is presented to it
> > * basically it groups ids in true_ids by grouping "close" values in true_dists
> > * "close"ness is determined by the absolute value difference of consecutive distances in true_dists ( treshold is <= 1e-6 )
> > * it uses the first element in a consecutive group as one of the subtraction operands
> > * it will also track the tie condition and surfaces the count of queries in query set with the tie condition
> > * recall_tests.py attempts to provide a comprehensive set of unit tests for both versions of recall (without and with ties)
> > * there is a run script for these tests ( tests/tests.sh ) which could be incorporated into a github action
> > 
> > Lowlights include:
> > 
> > * admittedly this recall-with-ties implementation could be faster using vectorization
> > * there are some slow tests in recall_tests.py which may slow down github push validation further if incorporated as-is as a branch push action
> 
> @sourcesync does this PR handle max inner product metric as well?

Good question @harsha-simhadri .  Yes, the implementation appears to work for all the knn-based datasets including text2image.  There is an additional test for text2image's distance array for decreasing monotonicity and it passes.  Because this implementation merely groups IDs based on "close"ness in the distance array, it appears to work for both L2 and inner-product.

Interestingly, it appears that all knn-based datasets have ties that need to be accounted for.  I think this means that we should update the baseline recall for all tracks:

187/10000 - bigann
110/10000 - deep1b
1323/100000- text2image
545/100000 - msturing
20669/29316 - msspacev

**Comment by maumueller** [comment]
@sourcesync 

Thanks! 

Two questions that I found a bit hard to answer from looking at the code:

1) Say I have 10,000,000 points, and the distance of the i-th neighbor to the query is (i + 1)*1e-7. Would your approach say that they are all duplicates by transitivity?
2) In general, if I ask for 10-NN recall, and I have 10 groups of 10 neighbors to a query, each group containting only near duplicates. Would the set of neighbors to compare to not include all of these 100 points? I think they shouldn't. 

In general, it seemed fine to me that we only considered ties to the `count`-th NN, and not care about any ties before that.

**Comment by sourcesync** [comment]
> @sourcesync
> 
> Thanks!

@maumueller Thanks for the feedback and questions.  My comments in-line:

> 
> Two questions that I found a bit hard to answer from looking at the code:
> 
> 1. Say I have 10,000,000 points, and the distance of the i-th neighbor to the query is (i + 1)*1e-7. Would your approach say that they are all duplicates by transitivity?

The first item in the "group" is always used to determine subsequent membership in the group.  In this way, if you add small deltas in the way you describe, at some point the difference between i and the first item in the group will be greater than 1e-6, thus terminating that group and starting a new one.

> 2. In general, if I ask for 10-NN recall, and I have 10 groups of 10 neighbors to a query, each group containting only near duplicates. Would the set of neighbors to compare to not include all of these 100 points? I think they shouldn't.

Yes it would include all 100 points.  How do you think this case should be handled?

> 
> In general, it seemed fine to me that we only considered ties to the `count`-th NN, and not care about any ties before that.
x

OK, lets make sure we are on the same page.  Let's consider the follow test case of 1 query in a query set and its response:

true_ids     = np.array([ [ 0,     1,      2,    3   ] ])
true_dists  = np.array([ [ 0.0,  0.0,  1.0,  2.0 ] ])
run_ids      = np.array([ [ 0,     1,              3   ]])
count=3

Notice that the distance tie is at the beginning.   If you start considering ties at count-1 in "true_dists" then I believe you would compute the recall as 2/3.  Is that the right example for what you were referring?

**Comment by maumueller** [comment]
> 
> > 1. In general, if I ask for 10-NN recall, and I have 10 groups of 10 neighbors to a query, each group containting only near duplicates. Would the set of neighbors to compare to not include all of these 100 points? I think they shouldn't.
> 
> Yes it would include all 100 points. How do you think this case should be handled?
> 

I think it would be wrong to take the 11-th point into consideration if we ask for the 10-NN recall. 


> > In general, it seemed fine to me that we only considered ties to the `count`-th NN, and not care about any ties before that.
> > x
> 
> OK, lets make sure we are on the same page. Let's consider the follow test case of 1 query in a query set and its response:
> 
> true_ids = np.array([ [ 0, 1, 2, 3 ] ]) true_dists = np.array([ [ 0.0, 0.0, 1.0, 2.0 ] ]) run_ids = np.array([ [ 0, 1, 3 ]]) count=3
> 
> Notice that the distance tie is at the beginning. If you start considering ties at count-1 in "true_dists" then I believe you would compute the recall as 2/3. Is that the right example for what you were referring?

Precisely, I think it should be 2/3. `3` is not among the 3-NN of the query.

**Comment by sourcesync** [comment]
> > > 1. In general, if I ask for 10-NN recall, and I have 10 groups of 10 neighbors to a query, each group containting only near duplicates. Would the set of neighbors to compare to not include all of these 100 points? I think they shouldn't.
> > 
> > 
> > Yes it would include all 100 points. How do you think this case should be handled?
> 
> I think it would be wrong to take the 11-th point into consideration if we ask for the 10-NN recall.
> 
> > > In general, it seemed fine to me that we only considered ties to the `count`-th NN, and not care about any ties before that.
> > > x
> > 
> > 
> > OK, lets make sure we are on the same page. Let's consider the follow test case of 1 query in a query set and its response:
> > true_ids = np.array([ [ 0, 1, 2, 3 ] ]) true_dists = np.array([ [ 0.0, 0.0, 1.0, 2.0 ] ]) run_ids = np.array([ [ 0, 1, 3 ]]) count=3
> > Notice that the distance tie is at the beginning. If you start considering ties at count-1 in "true_dists" then I believe you would compute the recall as 2/3. Is that the right example for what you were referring?
> 
> Precisely, I think it should be 2/3. `3` is not among the 3-NN of the query.

Great @maumueller  I see it now, thanks.  It looks like the previous proposal (ie, add corner case fix to the current implementation in the main branch) should work, but I'll want to adjust all the unit tests to make sure.

**Comment by sourcesync** [comment]
> ```python
> set_end = gt_size
> 
> for i in range(count, gt_size):
>   is_close = abs(dist_tie_check - true_dists[i] ) < 1e-6 
>   if not is_close:
>     set_end = i
>     break
> 
> found_tie = set_end > count
> ```

Great  @maumueller !  I changed the function per your suggestion and it passed all the unit tests.  @harsha-simhadri What do you think?  If you are good with it, I'll merge into main asap.

**Comment by sourcesync** [comment]
@harsha-simhadri  We are starting to use that new recall-with-ties function when evaluating T3 submissions.  So far, so good.  Given this change, we went ahead and re-measured the performance of the baseline for the T3 track and recomputed all the baseline benchmarks.  Since the baseline performance informs the submissions' score, we are going to notify T3 participants to expect new baseline performance numbers.  We will be changing the T3 README accordingly.  This also gives us the change to provide baselines for SSNPP as well as power and cost, which weren't yet available at the time.  This is just an FYI.

**Comment by sourcesync** [comment]
@harsha-simhadri @maumueller OK, T3 participants give the thumbs up on this and the updated T3 baselines based on it.  I'm going ahead with the merge.

**Pull request merged**
