### PR TITLE
[NeurIPS 2023 OOD] Update of parameters by team UTokyo

### PR DESCRIPTION
**Pull request by maronuu**
This is a PR that updates the parameter for `epsearch`.
The original PR is #197 .
If you encounter the same kind of issues described in #197 , please follow the comment in the PR.

Could you please re-run the alogrithm? Some part of construction can utilize cache in the previous evaluation.
Thank you for the patient evaluation and sorry for the multiple updates.

### CODE REVIEW

**Comment by maronuu** [comment]
I have no idea why the CI `Billion-Scale ANN Benchmarks, NeurIPS 2023 / build (sustech-ood, random-xs, ood) (pull_request) Failing after 27m` is failing...

**Comment by maronuu** [comment]
@harsha-simhadri
How can I re-run the CI?
I don't know why the CI `Billion-Scale ANN Benchmarks, NeurIPS 2023 / build (sustech-ood, random-xs, ood) (pull_request) Failing after 27m` is failing, since we I don't modify the config files related to CI, just changing the parameter file.

**Comment by maumueller** [comment]
> I have no idea why the CI `Billion-Scale ANN Benchmarks, NeurIPS 2023 / build (sustech-ood, random-xs, ood) (pull_request) Failing after 27m` is failing...

This is not related to your PR, so do not worry about it.

**Comment by maronuu** [comment]
# Note
Here is a note that might be helpful for organizers to evaluate our submission.

### Comment
Here are some notations that might be helpful to understand my source code

- `ep` in our source code means `entry point`.
- Dockerfile is much longer compared to other submission, sorry, but it installs minimum requirements for our submission.
- `ENV MKL_NUM_THREADS` or similar envs are introduced to make sure that our algoirthm fully utilizes the cores.

### Evaluation in my env
In my local environment, refining docker container using only 8 vCPU, and 16GB RAM,
we have:
- baseline diskann: ~1600 QPS
- our method: ~2400 QPS

And, in aws instance `c6i.2xlarge`, we have:
- baseline diskann: 3882 QPS
- our method: 4941 QPS

**Comment by maronuu** [comment]
# Note
Here is a note that might be helpful for organizers to evaluate our submission.

### Comment
Here are some notations that might be helpful to understand my source code


- Dockerfile is much longer compared to other submission, sorry, but it installs minimum requirements for our submission.
- `ENV MKL_NUM_THREADS` or similar envs are introduced to make sure that our algoirthm fully utilizes the cores.

### Evaluation in my env
In my local environment, refining docker container using only 8 vCPU, and 16GB RAM,
we have:
- baseline diskann: ~1600 QPS
- our method: ~2400 QPS

And, in aws instance `c6i.2xlarge`, we have:
- baseline diskann: 3882 QPS
- our method: 4941 QPS

**Pull request merged**
