### PR TITLE
[NeurIPS 2023 Filter Track] WM_filter 

### PR DESCRIPTION
**Pull request by alemagnani**
This is change of parameters from the first submission

Thanks to my teammate
Ashwani Rajan, SIjie Chen, Hongji Ye, and Zongjun Tan

and thanks for the organizers for setting this up

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
OK to merge without further testing on our part?

**Comment by alemagnani** [comment]
COuld you test it on the 10M dataset just in case? thanks

**Comment by harsha-simhadri** [comment]
I would be OK to merge, but can not offer to test again.

**Comment by alemagnani** [comment]
please don't merge then, i was hoping to see if the performance improvement i see on my vm are reflected on your server but i will leave it as is

**Comment by harsha-simhadri** [comment]
OK, if you are not interested in merging, can you please close the PR

**Pull request closed without merging**
