### PR TITLE
[NeurIPS 2023 Filter Track] DHQ

### PR DESCRIPTION
**Pull request by SDU-L**
This is the approximate nearest neighbor hybrid query algorithm DHQ by the iLearn team.

### CODE REVIEW

**Comment by SDU-L** [comment]
@maumueller，Hi，maumueller，We have just made minor modifications to adapt to the CI test, and the test of the standard data set has been carried out. Could you please help us check whether it can be merged? Thank you very much

**Comment by maumueller** [comment]
@SDU-L This worked fine and I got the following result

```
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 110, 'num': 2100, 'ef': 13, 'random': 35}))",yfcc-10M,10,13182.236171904644,0.0,3170.4788134098053,10957144.0,0,0,filter,0.900944
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 110, 'num': 2100, 'ef': 11, 'random': 40}))",yfcc-10M,10,13225.931251395536,0.0,3170.4788134098053,10957144.0,0,0,filter,0.901476
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 100, 'num': 2400, 'ef': 10, 'random': 30}))",yfcc-10M,10,13233.200747997102,0.0,3170.4788134098053,10957144.0,0,0,filter,0.9031750000000001
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 100, 'num': 2400, 'ef': 10, 'random': 45}))",yfcc-10M,10,13200.62079335457,0.0,3170.4788134098053,10957144.0,0,0,filter,0.9034369999999999
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 145, 'num': 2100, 'ef': 10, 'random': 35}))",yfcc-10M,10,13177.162497133217,0.0,3170.4788134098053,10957144.0,0,0,filter,0.908193
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 115, 'num': 2400, 'ef': 10, 'random': 30}))",yfcc-10M,10,13178.353223642753,0.0,3170.4788134098053,10957144.0,0,0,filter,0.9082839999999999
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 140, 'num': 2100, 'ef': 10, 'random': 42}))",yfcc-10M,10,13162.467555959027,0.0,3170.4788134098053,10957144.0,0,0,filter,0.908376
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 140, 'num': 2100, 'ef': 10, 'random': 41}))",yfcc-10M,10,13183.821486518696,0.0,3170.4788134098053,10957144.0,0,0,filter,0.908455
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 140, 'num': 2100, 'ef': 10, 'random': 36}))",yfcc-10M,10,13153.672335413276,0.0,3170.4788134098053,10957144.0,0,0,filter,0.908574
dhq,"DHQ((""DHQ({'L': 200, 'R': 24, 'level': 2})"", {'nprobe': 155, 'num': 2100, 'ef': 10, 'random': 35}))",yfcc-10M,10,13157.35831690874,0.0,3170.4788134098053,10957144.0,0,0,filter,0.909539
```

Merging this, thanks for your submission!

**Comment by SDU-L** [comment]
@maumueller  Hi，maumueller，Thank you very much for your work. May I ask whether the final result of the competition will be multiple tests for each algorithm to avoid the contingency caused by the hardware environment, etc. Thank you.

**Comment by maumueller** [comment]
We will run your implementation in isolation and use the same setup of repeating the workload 5 times.

**Comment by mdouze** [comment]
Hi DHQ team! 
I am preparing a few summary slides for the bigann challenge for the neurips track on Sat 16th.
Would you mind summarizing how your indexing works? Just comment here or send me some slides / doc... Thanks !

**Comment by SDU-L** [comment]
> Hi DHQ team! I am preparing a few summary slides for the bigann challenge for the neurips track on Sat 16th. Would you mind summarizing how your indexing works? Just comment here or send me some slides / doc... Thanks !

DHQ proposes a dynamic hybrid query retrieval framework. The framework first constructs an inverted label index for the original vectors in the dataset, and filters the labels according to the number of original vectors included. For the labels below the threshold, the IVF index is constructed, and the IVF algorithm is used to filter and search.
For labels that exceed the threshold, we build a KNNG for each label and randomly add entry nodes to increase the randomness of the search process, while using product quantization to speed up the vector similarity calculation. It is worth noting that we have optimized KNNG's memory to ensure that it meets track memory requirements. In addition, in the process of graph index routing, we weighted the distance of vectors that exceeded the label filtering conditions to ensure that their neighbors would not be filtered in advance.

**Pull request merged**
