### PR TITLE
[NeurIPS 2023 Filter Track] faissplus

### PR DESCRIPTION
**Pull request by PUITAR**
Our submission of algorithm 1: faissplus.

Using some parameters to optimize faiss.

### CODE REVIEW

**Comment by maumueller** [comment]
@PUITAR This seems to have the same problems as mentioned in #220. Please update your pull request to avoid changing the existing code base.

**Review by maumueller — CHANGES_REQUESTED** [review]
This doesn't install, see https://github.com/harsha-simhadri/big-ann-benchmarks/actions/runs/6705814792/job/18221013571?pr=222#step:4:1860.

**Comment by maumueller** [comment]
I'll try again, but please also fix the other issues where you remove files from our codebase.

**Comment by PUITAR** [comment]
> It still doesn't work: https://github.com/harsha-simhadri/big-ann-benchmarks/actions/runs/6706568601/job/18223474904?pr=222#step:4:1858

I‘m sorry we have so many problems with our code. I have just add a file to our `faissplus`, so run the action of ’install requirement‘ again may works.

**Comment by maumueller** [comment]
@PUITAR I don't see a new commit before the failing CI run that I am pointing to.

**Comment by PUITAR** [comment]
@maumueller I just realized some mistake. Since you might used the same docker to run the CI test, it wrong again.
you should see this, in the **INTALL REQUIREMENT** action of the [CI test](https://github.com/harsha-simhadri/big-ann-benchmarks/actions/runs/6706568601/job/18223474904?pr=222#step:4:1856), there is an error
``` shell
------
Dockerfile:15
--------------------
  13 |     RUN python3 -m pip install -r requirements_conda.txt 
  14 |     
  15 | >>> COPY neurips23/filter/faiss/bow_id_selector.swig ./
  16 |     
  17 |     RUN swig -c++ -python -I$CONDA_PREFIX/include -Ifaiss bow_id_selector.swig 
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 5de61ec8-c85c-4b78-898d-5c657cc86999::96cbz8xkkinfbz3umqxm8tzf3: "/neurips23/filter/faiss/bow_id_selector.swig": not found
```
This means the file(bow_id_selector.swig) lost, and i had add the file to my PR. So please run the intall requirement again. Thank you very much. orz

**Comment by maumueller** [comment]
@PUITAR  This looks much better. 

I got the following results: 

```
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 30, 'mt_threshold': 0.00033}))",yfcc-10M,10,3840.5696040105754,0.0,573.4747545719147,4905644.0,0,0,filter,0.895063
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 32, 'mt_threshold': 0.0003}))",yfcc-10M,10,3764.112198957016,0.0,573.4747545719147,4905644.0,0,0,filter,0.8968999999999999
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 32, 'mt_threshold': 0.00031}))",yfcc-10M,10,3756.703088341436,0.0,573.4747545719147,4905644.0,0,0,filter,0.897869
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 32, 'mt_threshold': 0.00033}))",yfcc-10M,10,3737.604998681685,0.0,573.4747545719147,4905644.0,0,0,filter,0.8996660000000001
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 34, 'mt_threshold': 0.0003}))",yfcc-10M,10,3673.341554167496,0.0,573.4747545719147,4905644.0,0,0,filter,0.901073
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 32, 'mt_threshold': 0.00035}))",yfcc-10M,10,3735.4637292410794,0.0,573.4747545719147,4905644.0,0,0,filter,0.901529
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 34, 'mt_threshold': 0.00031}))",yfcc-10M,10,3652.6801971503146,0.0,573.4747545719147,4905644.0,0,0,filter,0.902008
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 34, 'mt_threshold': 0.00033}))",yfcc-10M,10,3655.287962959017,0.0,573.4747545719147,4905644.0,0,0,filter,0.903754
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 34, 'mt_threshold': 0.00035}))",yfcc-10M,10,3635.117445737324,0.0,573.4747545719147,4905644.0,0,0,filter,0.9055630000000001
faissplus,"Faiss(('IVF11264,SQ8', {'nprobe': 40, 'mt_threshold': 0.0003}))",yfcc-10M,10,3453.915576495494,0.0,573.4747545719147,4905644.0,0,0,filter,0.9119970000000001
```

Is this ready to be merged?

**Review by maumueller — APPROVED** [review]

**Pull request merged**
