### PR TITLE
OOD/cufe

### PR DESCRIPTION
**Pull request by AliHashish**
team name: cufe
track: OOD

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@AliHashish  thanks for the PR. Could you please add a CI test? Also, could you please help me debug this (install.py returned with `success`)

```
(bigann) harshasi@dnode3:~/big-ann-benchmarks$ python run.py --dataset text2image-10M --neurips23track ood --algorithm cufe
file data/text2image1B/query.public.100K.fbin already exists
file data/text2image1B/text2image-10M already exists
file data/text2image1B/query.heldout.30K.fbin already exists
file data/text2image1B/gt100-heldout.30K.fbin already exists
file data/text2image1B/base.1B.fbin.crop_nb_10000000 already exists
2023-11-01 05:40:44,310 - annb - INFO - running only cufe
2023-11-01 05:40:44,333 - annb - INFO - Order: [Definition(algorithm='cufe', constructor='diskann', module='neurips23.ood.cufe.diskann-in-mem', docker_tag='neurips23-ood-cufe', docker_volumes=[], arguments=['ip', {'R': 64, 'L': 500, 'buildthreads': 32}], query_argument_groups=[[{'Ls': 30, 'T': 8}], [{'Ls': 50, 'T': 8}], [{'Ls': 70, 'T': 8}], [{'Ls': 100, 'T': 8}]], disabled=False)]
RW Namespace(dataset='text2image-10M', count=10, definitions='algos-2021.yaml', algorithm='cufe', docker_tag=None, list_algorithms=False, force=False, rebuild=False, runs=5, timeout=43200, max_n_algorithms=-1, power_capture='', t3=False, nodocker=False, upload_index=False, download_index=False, blob_prefix=None, sas_string=None, private_query=False, neurips23track='ood', runbook_path='neurips23/streaming/simple_runbook.yaml')
Setting container wait timeout to 43200 seconds
2023-11-01 05:40:44,738 - annb.c0fe65ecedca - INFO - Created container c0fe65ecedca: CPU limit 0-7, mem limit 14011165440, timeout 43200, command ['--dataset', 'text2image-10M', '--algorithm', 'cufe', '--module', 'neurips23.ood.cufe.diskann-in-mem', '--constructor', 'diskann', '--runs', '5', '--count', '10', '--neurips23track', 'ood', '["ip", {"R": 64, "L": 500, "buildthreads": 32}]', '[{"Ls": 30, "T": 8}]', '[{"Ls": 50, "T": 8}]', '[{"Ls": 70, "T": 8}]', '[{"Ls": 100, "T": 8}]']
2023-11-01 05:40:45,072 - annb.c0fe65ecedca - INFO - ['ip', {'R': 64, 'L': 500, 'buildthreads': 32}]
2023-11-01 05:40:45,072 - annb.c0fe65ecedca - INFO - Trying to instantiate neurips23.ood.cufe.diskann-in-mem.diskann(['ip', {'R': 64, 'L': 500, 'buildthreads': 32}])
2023-11-01 05:40:45,099 - annb.c0fe65ecedca - INFO - Traceback (most recent call last):
2023-11-01 05:40:45,099 - annb.c0fe65ecedca - INFO -   File "/home/app/run_algorithm.py", line 3, in <module>
2023-11-01 05:40:45,099 - annb.c0fe65ecedca - INFO -     run_from_cmdline()
2023-11-01 05:40:45,099 - annb.c0fe65ecedca - INFO -   File "/home/app/benchmark/runner.py", line 228, in run_from_cmdline
2023-11-01 05:40:45,102 - annb.c0fe65ecedca - INFO -     run(definition, args.dataset, args.count, args.runs, args.rebuild,
2023-11-01 05:40:45,102 - annb.c0fe65ecedca - INFO -   File "/home/app/benchmark/runner.py", line 33, in run
2023-11-01 05:40:45,102 - annb.c0fe65ecedca - INFO -     algo = instantiate_algorithm(definition)
2023-11-01 05:40:45,102 - annb.c0fe65ecedca - INFO -   File "/home/app/benchmark/algorithms/definitions.py", line 24, in instantiate_algorithm
2023-11-01 05:40:45,105 - annb.c0fe65ecedca - INFO -     constructor = getattr(module, definition.constructor)
2023-11-01 05:40:45,105 - annb.c0fe65ecedca - INFO - AttributeError: module 'neurips23.ood.cufe.diskann-in-mem' has no attribute 'diskann'. Did you mean: 'diskannpy'?
2023-11-01 05:40:45,367 - annb.c0fe65ecedca - ERROR - ['ip', {'R': 64, 'L': 500, 'buildthreads': 32}]
Trying to instantiate neurips23.ood.cufe.diskann-in-mem.diskann(['ip', {'R': 64, 'L': 500, 'buildthreads': 32}])
Traceback (most recent call last):
  File "/home/app/run_algorithm.py", line 3, in <module>
    run_from_cmdline()
  File "/home/app/benchmark/runner.py", line 228, in run_from_cmdline
    run(definition, args.dataset, args.count, args.runs, args.rebuild,
  File "/home/app/benchmark/runner.py", line 33, in run
    algo = instantiate_algorithm(definition)
  File "/home/app/benchmark/algorithms/definitions.py", line 24, in instantiate_algorithm
    constructor = getattr(module, definition.constructor)
AttributeError: module 'neurips23.ood.cufe.diskann-in-mem' has no attribute 'diskann'. Did you mean: 'diskannpy'?

2023-11-01 05:40:45,368 - annb.c0fe65ecedca - ERROR - Child process for container c0fe65ecedcareturned exit code 1 with message
```

**Comment by AliHashish** [comment]
@harsha-simhadri 
I had added my CI test in the nerupis23.yml workflows. 
As for the error, it should e fixed now. It seems that I had not changed one of the constructors, which was causing this error. Thank you

**Comment by maumueller** [comment]
@AliHashish I do not see the CI entry for your entry. Please add it before I'm going to merge your entry.

**Comment by AbdelrahmanMohamed129** [comment]
> @AliHashish I do not see the CI entry for your entry. Please add it before I'm going to merge your entry.

I added the CI entry

**Comment by harsha-simhadri** [comment]
There are numbers I see on Azure VM:

```
cufe,"diskann(('R64_L500', {'Ls': 30, 'T': 8}))",text2image-10M,10,8308.53021957315,0.0,-1.0,11084980.0,0,0,ood,0.790859
cufe,"diskann(('R64_L500', {'Ls': 50, 'T': 8}))",text2image-10M,10,6381.206812352822,0.0,-1.0,11084980.0,0,0,ood,0.852343
cufe,"diskann(('R64_L500', {'Ls': 70, 'T': 8}))",text2image-10M,10,5248.466007978116,0.0,-1.0,11084980.0,0,0,ood,0.885197
cufe,"diskann(('R64_L500', {'Ls': 100, 'T': 8}))",text2image-10M,10,4186.853995737066,0.0,-1.0,11084980.0,0,0,ood,0.9141870000000001
```

**Comment by harsha-simhadri** [comment]
I am going to merge this PR. @AbdelrahmanMohamed129 please let me know if anything needs to be reconsidered/

**Pull request merged**
