### PR TITLE
YFCC filtered dataset

### PR DESCRIPTION
**Pull request by mdouze**
This PR adds the new YFCC dataset. It contains the metadata extraction and formatting and the ground-truth distrance computations. 

TODO: 
- sync with Frank Liu to get actual CLIP descriptiors rather than dummy ones 
- automatic download code 
- upload to AWS

### CODE REVIEW

**Comment by maumueller** [comment]
Nice! Is it correctly understood that you propose splitting up the query workload into a file holding the dense set of vectors and one sparse matrix that contains the filters?  This seems like a fine solution to me.

**Comment by mdouze** [comment]
@maumueller yes right, the dense part is in the "standard" format for the other competition datasets.

**Comment by mdouze** [comment]
Upload to AWS done, but I am waiting to have the final dense features to implement the download.

**Comment by mdouze** [comment]
The current results are running with descriptors from 
https://github.com/facebookresearch/low-shot-with-diffusion
(not the CLIP descriptors)
The baseline results get the following tradeoffs: 

image

For each query, given the query terms, the engine estimates the fraction of the dataset that will have these terms. 
mt is the break-down factor to chose metadata first or filtering first. It seems that for 90% Recall, the break-down factor is around 0.0003, yielding 60% IVF searches and 40% metadata searches. This seems balanced, which validates the dataset.

Commands to obtain these resutls: 

- install Faiss with conda: see https://github.com/facebookresearch/faiss/blob/main/INSTALL.md

- compile module: 
```bash

  cd track1_baseline_faiss/  
  swig -c++ -python -I$CONDA_PREFIX/include  bow_id_selector.swig 
  g++ -shared -O3 -g -fPIC bow_id_selector_wrap.cxx -o _bow_id_selector.so  \
      -I $( python -c "import distutils.sysconfig ; print(distutils.sysconfig.get_python_inc())" )   \
      -I $CONDA_PREFIX/include $CONDA_PREFIX/lib/libfaiss_avx2.so

```

- download data: 
```
cd data/yfcc100M/
for i in dummy2.GT.public.ibin dummy2.base.10M.u8bin  dummy2.query.public.100K.u8bin dummy2.unfiltered.GT.public.ibin
do 
    wget dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/yfcc100M/$i 
done

```
(dummy2 means that this is using resnet50 descriptors rather than CLIP descriptors)

- build index: 
```
PYTHONPATH=.  python  track1_baseline_faiss/baseline_faiss_filtered.py \
    --dataset yfcc-10M --indexname data/yfcc100M/baseline_index_ivf16ksq_binsig0.1.faissindex \
    --indexkey IVF16384,SQ8 \
    --binarysig --binarysig_proba1 0.1 --binarysig_file data/yfcc100M/baseline_index_ivf16ksq_binsig0.1.pickle  
    --build
```

- perform search: 
```
mt=0.0003 ; np=96; 
PYTHONPATH=. python  track1_baseline_faiss/baseline_faiss_filtered.py \
   --dataset yfcc-10M --indexname data/yfcc100M/baseline_index_ivf16ksq_binsig0.1.faissindex \
   --binarysig --binarysig_file data/yfcc100M/baseline_index_ivf16ksq_binsig0.1.pickle \
   --nprobe $np --metadata_threshold $mt --nt 16

```
Runs in 22.8 s (43k QPS) for a recall of 0.91 (full result [here](https://gist.github.com/mdouze/809ce5a6c01f0f75949f0a17d37c1814))

**Review by maumueller — APPROVED** [review]

**Comment by maumueller** [comment]
Merging this to start the overall refactoring.

**Pull request merged**
