### PR TITLE
Fix CI runs

### PR DESCRIPTION
**Pull request by maumueller**

### CODE REVIEW

**Comment by maumueller** [comment]
@NJU-yasuo I looked into your fork https://github.com/NJU-yasuo/big-ann-benchmarks, but
 faiss submodule is not part of the repo. Is this standard FAISS or a custom version? For the latter, could you make it available? It would be unfortunate to not your implementation available in the benchmark. Thanks!

@mdouze The `kst` implementation seems to use the following factory for FAISS "OPQ32_64,IVF1024_HNSWlibFp32_32,PQ64x4fsr" (index builds successfully), but then fails setting the parameters from [the config](https://github.com/harsha-simhadri/big-ann-benchmarks/blob/main/algos-2021.yaml#L117-L131)

```
Running query argument group 1 of 2...
Traceback (most recent call last):
  File "run_algorithm.py", line 3, in <module>
    run_from_cmdline()
  File "/home/app/benchmark/runner.py", line 236, in run_from_cmdline
    run(definition, args.dataset, args.count, args.runs, args.rebuild,
  File "/home/app/benchmark/runner.py", line 129, in run
    algo.set_query_arguments(*query_arguments)
  File "/home/app/benchmark/algorithms/opt_faiss.py", line 290, in set_query_arguments
    self.ps.set_index_parameters(self.index, query_args)
  File "/root/anaconda3/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 5619, in set_index_parameters
    return _swigfaiss_avx2.ParameterSpace_set_index_parameters(self, *args)
RuntimeError: Error in virtual void faiss::ParameterSpace::set_index_parameter(faiss::Index*, const string&, double) const at /opt/conda/conda-bld/faiss-pkg_1623024438023/work/faiss/AutoTune.cpp:550: ParameterSpace::set_index_parameter:could not set parameter efSearch
```

Maybe you have an idea?

**Comment by maumueller** [comment]
@masajiro I removed NGT from the codebase for now because you removed the branch upstream in your directory.

**Comment by mdouze** [comment]
HNSWlibFp32_32 is custom code. Maybe they did not implement setting efSearch in the code?

**Comment by NJU-yasuo** [comment]
@maumueller  it is public now, can u see it ?

**Comment by maumueller** [comment]
Thanks @NJU-yasuo! It builds successfully in CI, but there seems to be some general, unrelated problem that causes everything to fail.

**Comment by maumueller** [comment]
@harsha-simhadri  @sourcesync  This seems to be working, except for a mid-run crash of `puck`. I think we should merge this.

**Pull request merged**
