### PR TITLE
[NeurIPS 2023 OOD track] SUSTech-OOD submission

### PR DESCRIPTION
**Pull request by whateveraname**
This is the submission of our team. Please check it out and inform us if there is anything needed.

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
The install fails with the following message. could you please help?

```
[+] Building 1.7s (6/17)                                                                                                                                                                                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                               0.0s
 => => transferring dockerfile: 483B                                                                                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                  0.0s
 => => transferring context: 66B                                                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/neurips23:latest                                                                                                                                                                                                                0.0s
 => [ 1/14] FROM docker.io/library/neurips23                                                                                                                                                                                                                                       0.0s
 => CACHED [ 2/14] RUN apt update                                                                                                                                                                                                                                                  0.0s
 => ERROR [ 3/14] RUN apt install -y libssl-dev                                                                                                                                                                                                                                    1.7s
------
 > [ 3/14] RUN apt install -y libssl-dev:
0.333
0.333 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

**Comment by whateveraname** [comment]
It seems that the networking didn't work well. I also encountered 404 error when installing libssl-dev on my server once.  But I see the CI of our algo passed successfully. Maybe you could retry or change another VM?

**Comment by harsha-simhadri** [comment]
Yes, I am retrying on another machine. Will update soon.

**Comment by harsha-simhadri** [comment]
@whateveraname  Are these results in line with your experiments?

```
sustech-ood,"{'ef': 95, 'nprobe': 30})",text2image-10M,10,18257.143721492965,0.0,5605.981101036072,7591056.0,0,0,ood,0.867797
sustech-ood,"{'ef': 115, 'nprobe': 30})",text2image-10M,10,15956.991529977777,0.0,5605.981101036072,7591056.0,0,0,ood,0.8860060000000001
sustech-ood,"{'ef': 125, 'nprobe': 30})",text2image-10M,10,15038.507657125507,0.0,5605.981101036072,7591056.0,0,0,ood,0.893469
sustech-ood,"{'ef': 130, 'nprobe': 30})",text2image-10M,10,14646.81916250362,0.0,5605.981101036072,7591056.0,0,0,ood,0.8967940000000001
sustech-ood,"{'ef': 135, 'nprobe': 30})",text2image-10M,10,14220.647840196458,0.0,5605.981101036072,7591056.0,0,0,ood,0.8998519999999999
sustech-ood,"{'ef': 140, 'nprobe': 30})",text2image-10M,10,13836.731735609052,0.0,5605.981101036072,7591056.0,0,0,ood,0.9029999999999999
sustech-ood,"{'ef': 145, 'nprobe': 30})",text2image-10M,10,13528.888259837238,0.0,5605.981101036072,7591056.0,0,0,ood,0.90564
sustech-ood,"{'ef': 155, 'nprobe': 30})",text2image-10M,10,12840.446544524726,0.0,5605.981101036072,7591056.0,0,0,ood,0.910611
sustech-ood,"{'ef': 175, 'nprobe': 30})",text2image-10M,10,11683.389174065982,0.0,5605.981101036072,7591056.0,0,0,ood,0.9192259999999999
```

**Comment by whateveraname** [comment]
@harsha-simhadri Yes, the QPS aligns with ours. Really appreciate for your patient evaluation!

**Pull request merged**
