### PR TITLE
[NeurIPS 2023 OOD Track] Puck-fizz

### PR DESCRIPTION
**Pull request by nk2014yj**
Improve the quality of puck index using query dataset

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@nk2014yj I see the following error in running this. could you please help debug?

```
Call stack:
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harshasi/big-ann-benchmarks/benchmark/runner.py", line 316, in stream_logs
    logger.info(colors.color(line.decode().rstrip(), fg='blue'))
Message: '\x1b[34m    algo.fit(dataset)\x1b[0m'
Arguments: ()
2023-10-30 18:11:11,281 - annb.7f43dda97eb2 - ERROR - ['ip', {'index_type': 2, 'C': 1000, 'F': 1000, 'tinker_neighborhood': 16, 'tinker_construction': 200}]
Trying to instantiate neurips23.ood.puck-fizz.puck.Puck(['ip', {'index_type': 2, 'C': 1000, 'F': 1000, 'tinker_neighborhood': 16, 'tinker_construction': 200}])
Running puck-fizz on text2image-10M
Loading index
self.topk=10
data/text2image-10M.C1000_F1000_Neighborhood16_Construction200.puckindex
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1030 18:09:38.450278     1 hierarchical_cluster_index.cpp:199] 1
E1030 18:09:38.450315     1 hierarchical_cluster_index.cpp:641] model file data/text2image-10M.C1000_F1000_Neighborhood16_Construction200.puckindex/index.dat stat error
I1030 18:09:38.450323     1 hierarchical_cluster_index.cpp:199] 1
I1030 18:09:38.450325     1 py_api_wrapper.cpp:90] init index of Flat
I1030 18:09:38.450327     1 hierarchical_cluster_index.cpp:217] start init index.
E1030 18:09:38.450331     1 hierarchical_cluster_index.cpp:641] model file data/text2image-10M.C1000_F1000_Neighborhood16_Construction200.puckindex/index.dat stat error
E1030 18:09:38.450333     1 hierarchical_cluster_index.cpp:221] read_model_file has error.
E1030 18:09:38.450336     1 py_api_wrapper.cpp:97] load index Faild
Error grabbing logs: unexpected EOF

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1104, in emit
    self.flush()
  File "/usr/lib/python3.10/logging/__init__.py", line 1084, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/home/harshasi/big-ann-benchmarks/run.py", line 6, in <module>
    main()
  File "/home/harshasi/big-ann-benchmarks/benchmark/main.py", line 267, in main
    [worker.start() for worker in workers]
  File "/home/harshasi/big-ann-benchmarks/benchmark/main.py", line 267, in <listcomp>
    [worker.start() for worker in workers]
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harshasi/big-ann-benchmarks/benchmark/main.py", line 58, in run_worker
    run_docker(definition, args.dataset, args.count,
  File "/home/harshasi/big-ann-benchmarks/benchmark/runner.py", line 323, in run_docker
    _handle_container_return_value(return_value, container, logger)
  File "/home/harshasi/big-ann-benchmarks/benchmark/runner.py", line 343, in _handle_container_return_value
    logger.error(colors.color(container.logs().decode(), fg='red'))
Message: "\x1b[31m['ip', {'index_type': 2, 'C': 1000, 'F': 1000, 'tinker_neighborhood': 16, 'tinker_construction': 200}]\nTrying to instantiate neurips23.ood.puck-fizz.puck.Puck(['ip', {'index_type': 2, 'C': 1000, 'F': 1000, 'tinker_neighborhood': 16, 'tinker_construction': 200}])\nRunning puck-fizz on text2image-10M\nLoading index\nself.topk=10\ndata/text2image-10M.C1000_F1000_Neighborhood16_Construction200.puckindex\nWARNING: Logging before InitGoogleLogging() is written to STDERR\nI1030 18:09:38.450278     1 hierarchical_cluster_index.cpp:199] 1\nE1030 18:09:38.450315     1 hierarchical_cluster_index.cpp:641] model file data/text2image-10M.C1000_F1000_Neighborhood16_Construction200.puckindex/index.dat stat error\nI1030 18:09:38.450323     1 hierarchical_cluster_index.cpp:199] 1\nI1030 18:09:38.450325     1 py_api_wrapper.cpp:90] init index of Flat\nI1030 18:09:38.450327     1 hierarchical_cluster_index.cpp:217] start init index.\nE1030 18:09:38.450331     1 hierarchical_cluster_index.cpp:641] model file data/text2image-10M.C1000_F1000_Neighborhood16_Construction200.puckindex/index.dat stat error\nE1030 18:09:38.450333     1 hierarchical_cluster_index.cpp:221] read_model_file has error.\nE1030 18:09:38.450336     1 py_api_wrapper.cpp:97] load index Faild\nError grabbing logs: unexpected EOF\n\x1b[0m"
Arguments: ()
2023-10-30 18:11:11,291 - annb.7f43dda97eb2 - ERROR - Child process for container 7f43dda97eb2returned exit code 1 with message
```

**Comment by nk2014yj** [comment]
It seems that there is an error when loading the index, and most likely the index has not been created.
I will check the logic of the loading.

**Comment by nk2014yj** [comment]
I noticed this prompt.

image

Puck will write the index file to the disk after the index construction is completed.
The high probability is that the disk is full and the writing of the index file fails, resulting in the failure to load the index.

would you please reserve about 20G of disk space to Puck-fizz and try  this task with --rebuild again?

**Comment by harsha-simhadri** [comment]
sorry for missing that. will rerun

**Comment by maumueller** [comment]
Thanks for your submission, I'm merging this. I got the following results on the public query workload

```
puck-fizz,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 160})",text2image-10M,10,8360.695317042335,0.0,11834.989310264587,13784464.0,0,0,ood,0.9015930000000001
puck-fizz,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 170})",text2image-10M,10,8007.0695352322755,0.0,11834.989310264587,13784464.0,0,0,ood,0.905934
puck-fizz,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 180})",text2image-10M,10,7693.455517487063,0.0,11834.989310264587,13784464.0,0,0,ood,0.910122
puck-fizz,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 190})",text2image-10M,10,7396.522235907129,0.0,11834.989310264587,13784464.0,0,0,ood,0.9137890000000001
```

**Pull request merged**
