### PR TITLE
[NeurIPS 2023 OOD Track] pyanns

### PR DESCRIPTION
**Pull request by veaaaab**

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@veaaaab  thanks for the PR. Could you please help me debug this:

```
:~/big-ann-benchmarks$ python install.py --neurips23track ood --algorithm pyanns
Building base image...
[+] Building 0.7s (13/13) FINISHED                                                                                         docker:default
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 66B                                                                                                     0.0s
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 556B                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:jammy                                                                      0.6s
 => [1/8] FROM docker.io/library/ubuntu:jammy@sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449fecac8176c6e496e5c1f05f                0.0s
 => [internal] load build context                                                                                                    0.0s
 => => transferring context: 80B                                                                                                     0.0s
 => CACHED [2/8] RUN apt-get update && apt-get install -y python3-numpy python3-scipy python3-pip build-essential git axel wget      0.0s
 => CACHED [3/8] RUN wget https://aka.ms/downloadazcopy-v10-linux && mv downloadazcopy-v10-linux azcopy.tgz && tar xzf azcopy.tgz -  0.0s
 => CACHED [4/8] RUN cp azcopy_folder/azcopy /usr/bin                                                                                0.0s
 => CACHED [5/8] RUN pip3 install -U pip                                                                                             0.0s
 => CACHED [6/8] WORKDIR /home/app                                                                                                   0.0s
 => CACHED [7/8] COPY requirements_py3.10.txt run_algorithm.py ./                                                                    0.0s
 => CACHED [8/8] RUN pip3 install -r requirements_py3.10.txt                                                                         0.0s
 => exporting to image                                                                                                               0.0s
 => => exporting layers                                                                                                              0.0s
 => => writing image sha256:d4ba00651ac26c1695d50241b666fade05e69b30b7babc158d71f509910e20a5                                         0.0s
 => => naming to docker.io/library/neurips23                                                                                         0.0s
Building algorithm images... with (1) processes
Building neurips23-ood-pyanns...
docker build  --rm -t neurips23-ood-pyanns -f neurips23/ood/pyanns/Dockerfile .
[+] Building 52.3s (11/22)                                                                                                 docker:default
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 864B                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 66B                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/neurips23:latest                                                                  0.0s
 => [ 1/19] FROM docker.io/library/neurips23                                                                                         0.0s
 => CACHED [ 2/19] RUN apt update                                                                                                    0.0s
 => CACHED [ 3/19] RUN apt install -y software-properties-common                                                                     0.0s
 => CACHED [ 4/19] RUN add-apt-repository -y ppa:git-core/ppa                                                                        0.0s
 => [ 5/19] RUN DEBIAN_FRONTEND=noninteractive apt install -y git make cmake g++ libaio-dev libgoogle-perftools-dev libunwind-dev   50.2s
 => [ 6/19] RUN git clone https://github.com/veaaaab/DiskANN.git --branch  bigann23_ood                                              1.4s
 => [ 7/19] WORKDIR /home/app/DiskANN                                                                                                0.1s
 => ERROR [ 8/19] RUN python3 -m build                                                                                               0.5s
------
 > [ 8/19] RUN python3 -m build:
0.357 /usr/bin/python3: No module named build
------
Dockerfile:10
--------------------
   8 |     RUN git clone https://github.com/veaaaab/DiskANN.git --branch  bigann23_ood
   9 |     WORKDIR /home/app/DiskANN
  10 | >>> RUN python3 -m build
  11 |     RUN pip install dist/diskannpy-0.5.0rc3.post1-cp310-cp310-linux_x86_64.whl
  12 |     WORKDIR /home/app
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m build" did not complete successfully: exit code: 1


Install Status:
{'neurips23-ood-pyanns': 'fail'}
```

**Comment by veaaaab** [comment]
Thanks for your reply. I've pushed the fix, could you please test it again

> @veaaaab thanks for the PR. Could you please help me debug this:
> 
> ```
> :~/big-ann-benchmarks$ python install.py --neurips23track ood --algorithm pyanns
> Building base image...
> [+] Building 0.7s (13/13) FINISHED                                                                                         docker:default
>  => [internal] load .dockerignore                                                                                                    0.0s
>  => => transferring context: 66B                                                                                                     0.0s
>  => [internal] load build definition from Dockerfile                                                                                 0.0s
>  => => transferring dockerfile: 556B                                                                                                 0.0s
>  => [internal] load metadata for docker.io/library/ubuntu:jammy                                                                      0.6s
>  => [1/8] FROM docker.io/library/ubuntu:jammy@sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449fecac8176c6e496e5c1f05f                0.0s
>  => [internal] load build context                                                                                                    0.0s
>  => => transferring context: 80B                                                                                                     0.0s
>  => CACHED [2/8] RUN apt-get update && apt-get install -y python3-numpy python3-scipy python3-pip build-essential git axel wget      0.0s
>  => CACHED [3/8] RUN wget https://aka.ms/downloadazcopy-v10-linux && mv downloadazcopy-v10-linux azcopy.tgz && tar xzf azcopy.tgz -  0.0s
>  => CACHED [4/8] RUN cp azcopy_folder/azcopy /usr/bin                                                                                0.0s
>  => CACHED [5/8] RUN pip3 install -U pip                                                                                             0.0s
>  => CACHED [6/8] WORKDIR /home/app                                                                                                   0.0s
>  => CACHED [7/8] COPY requirements_py3.10.txt run_algorithm.py ./                                                                    0.0s
>  => CACHED [8/8] RUN pip3 install -r requirements_py3.10.txt                                                                         0.0s
>  => exporting to image                                                                                                               0.0s
>  => => exporting layers                                                                                                              0.0s
>  => => writing image sha256:d4ba00651ac26c1695d50241b666fade05e69b30b7babc158d71f509910e20a5                                         0.0s
>  => => naming to docker.io/library/neurips23                                                                                         0.0s
> Building algorithm images... with (1) processes
> Building neurips23-ood-pyanns...
> docker build  --rm -t neurips23-ood-pyanns -f neurips23/ood/pyanns/Dockerfile .
> [+] Building 52.3s (11/22)                                                                                                 docker:default
>  => [internal] load build definition from Dockerfile                                                                                 0.0s
>  => => transferring dockerfile: 864B                                                                                                 0.0s
>  => [internal] load .dockerignore                                                                                                    0.0s
>  => => transferring context: 66B                                                                                                     0.0s
>  => [internal] load metadata for docker.io/library/neurips23:latest                                                                  0.0s
>  => [ 1/19] FROM docker.io/library/neurips23                                                                                         0.0s
>  => CACHED [ 2/19] RUN apt update                                                                                                    0.0s
>  => CACHED [ 3/19] RUN apt install -y software-properties-common                                                                     0.0s
>  => CACHED [ 4/19] RUN add-apt-repository -y ppa:git-core/ppa                                                                        0.0s
>  => [ 5/19] RUN DEBIAN_FRONTEND=noninteractive apt install -y git make cmake g++ libaio-dev libgoogle-perftools-dev libunwind-dev   50.2s
>  => [ 6/19] RUN git clone https://github.com/veaaaab/DiskANN.git --branch  bigann23_ood                                              1.4s
>  => [ 7/19] WORKDIR /home/app/DiskANN                                                                                                0.1s
>  => ERROR [ 8/19] RUN python3 -m build                                                                                               0.5s
> ------
>  > [ 8/19] RUN python3 -m build:
> 0.357 /usr/bin/python3: No module named build
> ------
> Dockerfile:10
> --------------------
>    8 |     RUN git clone https://github.com/veaaaab/DiskANN.git --branch  bigann23_ood
>    9 |     WORKDIR /home/app/DiskANN
>   10 | >>> RUN python3 -m build
>   11 |     RUN pip install dist/diskannpy-0.5.0rc3.post1-cp310-cp310-linux_x86_64.whl
>   12 |     WORKDIR /home/app
> --------------------
> ERROR: failed to solve: process "/bin/sh -c python3 -m build" did not complete successfully: exit code: 1
> 
> 
> Install Status:
> {'neurips23-ood-pyanns': 'fail'}
> ```

Thanks for your reply. I've pushed the fix, could you please test it again

**Comment by harsha-simhadri** [comment]
I am able to run it now. Are these results in line with your experiments..
```
pyanns,pyanns(R48_L500)_ef90,text2image-10M,10,23431.354097237316,0.0,6322.670822143555,12137580.0,0,0,ood,0.886506
pyanns,pyanns(R48_L500)_ef95,text2image-10M,10,22750.970060016658,0.0,6322.670822143555,12137580.0,0,0,ood,0.891129
pyanns,pyanns(R48_L500)_ef100,text2image-10M,10,21863.352379586177,0.0,6322.670822143555,12137580.0,0,0,ood,0.8954610000000001
pyanns,pyanns(R48_L500)_ef102,text2image-10M,10,21589.111064580014,0.0,6322.670822143555,12137580.0,0,0,ood,0.8972289999999999
pyanns,pyanns(R48_L500)_ef104,text2image-10M,10,21576.16283564924,0.0,6322.670822143555,12137580.0,0,0,ood,0.899081
pyanns,pyanns(R48_L500)_ef106,text2image-10M,10,21532.09628410368,0.0,6322.670822143555,12137580.0,0,0,ood,0.900665
pyanns,pyanns(R48_L500)_ef108,text2image-10M,10,21198.680823973536,0.0,6322.670822143555,12137580.0,0,0,ood,0.9022030000000001
pyanns,pyanns(R48_L500)_ef110,text2image-10M,10,20758.805557393665,0.0,6322.670822143555,12137580.0,0,0,ood,0.903647
pyanns,pyanns(R48_L500)_ef115,text2image-10M,10,19910.24897637455,0.0,6322.670822143555,12137580.0,0,0,ood,0.907281
pyanns,pyanns(R48_L500)_ef120,text2image-10M,10,19289.514816023835,0.0,6322.670822143555,12137580.0,0,0,ood,0.9106669999999999
pyanns,pyanns(R48_L500)_ef125,text2image-10M,10,18874.200019619824,0.0,6322.670822143555,12137580.0,0,0,ood,0.913669
pyanns,pyanns(R48_L500)_ef130,text2image-10M,10,18939.6369244855,0.0,6322.670822143555,12137580.0,0,0,ood,0.9164770000000001
```

**Comment by veaaaab** [comment]
> I am able to run it now. Are these results in line with your experiments..
> 
> ```
> pyanns,pyanns(R48_L500)_ef90,text2image-10M,10,23431.354097237316,0.0,6322.670822143555,12137580.0,0,0,ood,0.886506
> pyanns,pyanns(R48_L500)_ef95,text2image-10M,10,22750.970060016658,0.0,6322.670822143555,12137580.0,0,0,ood,0.891129
> pyanns,pyanns(R48_L500)_ef100,text2image-10M,10,21863.352379586177,0.0,6322.670822143555,12137580.0,0,0,ood,0.8954610000000001
> pyanns,pyanns(R48_L500)_ef102,text2image-10M,10,21589.111064580014,0.0,6322.670822143555,12137580.0,0,0,ood,0.8972289999999999
> pyanns,pyanns(R48_L500)_ef104,text2image-10M,10,21576.16283564924,0.0,6322.670822143555,12137580.0,0,0,ood,0.899081
> pyanns,pyanns(R48_L500)_ef106,text2image-10M,10,21532.09628410368,0.0,6322.670822143555,12137580.0,0,0,ood,0.900665
> pyanns,pyanns(R48_L500)_ef108,text2image-10M,10,21198.680823973536,0.0,6322.670822143555,12137580.0,0,0,ood,0.9022030000000001
> pyanns,pyanns(R48_L500)_ef110,text2image-10M,10,20758.805557393665,0.0,6322.670822143555,12137580.0,0,0,ood,0.903647
> pyanns,pyanns(R48_L500)_ef115,text2image-10M,10,19910.24897637455,0.0,6322.670822143555,12137580.0,0,0,ood,0.907281
> pyanns,pyanns(R48_L500)_ef120,text2image-10M,10,19289.514816023835,0.0,6322.670822143555,12137580.0,0,0,ood,0.9106669999999999
> pyanns,pyanns(R48_L500)_ef125,text2image-10M,10,18874.200019619824,0.0,6322.670822143555,12137580.0,0,0,ood,0.913669
> pyanns,pyanns(R48_L500)_ef130,text2image-10M,10,18939.6369244855,0.0,6322.670822143555,12137580.0,0,0,ood,0.9164770000000001
> ```

It's a bit lower than expected, but it's ok to merge. Thanks!

**Comment by harsha-simhadri** [comment]
@veaaaab  What is the CMT entry corresponding to this entry? You could reach out to me via email too if do not want to list here.

**Pull request merged**
