### PR TITLE
[NeurIPS 2023 Sparse Track] pyanns

### PR DESCRIPTION
**Pull request by veaaaab**

### CODE REVIEW

**Comment by maumueller** [comment]
This worked well and I got the following results:

```
pyanns,pyanns_qdrop0.1_ef50,sparse-full,10,9229.639748787902,0.0,30585.41286110878,14783664.0,0,0,sparse,0.8961031518624643
pyanns,pyanns_qdrop0.08_ef50,sparse-full,10,8709.027857890163,0.0,30585.41286110878,14783664.0,0,0,sparse,0.8987679083094555
pyanns,pyanns_qdrop0.1_ef55,sparse-full,10,8638.189807279907,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9031518624641833
pyanns,pyanns_qdrop0.08_ef55,sparse-full,10,8166.033286435839,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9058166189111748
pyanns,pyanns_qdrop0.1_ef60,sparse-full,10,8166.903481477886,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9083667621776504
pyanns,pyanns_qdrop0.08_ef60,sparse-full,10,7699.447851373166,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9103438395415473
pyanns,pyanns_qdrop0.1_ef65,sparse-full,10,7710.621248227489,0.0,30585.41286110878,14783664.0,0,0,sparse,0.914727793696275
pyanns,pyanns_qdrop0.08_ef65,sparse-full,10,7296.230574532288,0.0,30585.41286110878,14783664.0,0,0,sparse,0.916647564469914
pyanns,pyanns_qdrop0.1_ef70,sparse-full,10,7304.167282910146,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9198710601719198
pyanns,pyanns_qdrop0.08_ef70,sparse-full,10,6928.843598434278,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9218338108882522
pyanns,pyanns_qdrop0.1_ef75,sparse-full,10,6986.467927685548,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9243409742120343
pyanns,pyanns_qdrop0.08_ef75,sparse-full,10,6550.183558450218,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9270916905444126
pyanns,pyanns_qdrop0.1_ef80,sparse-full,10,6641.110968200012,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9282521489971346
pyanns,pyanns_qdrop0.08_ef80,sparse-full,10,6275.986771574277,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9311174785100287
```

Please note that you can submit at most 10 search configurations, so please remove some search parameters (without adding new since the deadline has passed.)

**Review by maumueller — CHANGES_REQUESTED** [review]
Please remove search configurations.

**Comment by veaaaab** [comment]
> This worked well and I got the following results:
> 
> ```
> pyanns,pyanns_qdrop0.1_ef50,sparse-full,10,9229.639748787902,0.0,30585.41286110878,14783664.0,0,0,sparse,0.8961031518624643
> pyanns,pyanns_qdrop0.08_ef50,sparse-full,10,8709.027857890163,0.0,30585.41286110878,14783664.0,0,0,sparse,0.8987679083094555
> pyanns,pyanns_qdrop0.1_ef55,sparse-full,10,8638.189807279907,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9031518624641833
> pyanns,pyanns_qdrop0.08_ef55,sparse-full,10,8166.033286435839,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9058166189111748
> pyanns,pyanns_qdrop0.1_ef60,sparse-full,10,8166.903481477886,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9083667621776504
> pyanns,pyanns_qdrop0.08_ef60,sparse-full,10,7699.447851373166,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9103438395415473
> pyanns,pyanns_qdrop0.1_ef65,sparse-full,10,7710.621248227489,0.0,30585.41286110878,14783664.0,0,0,sparse,0.914727793696275
> pyanns,pyanns_qdrop0.08_ef65,sparse-full,10,7296.230574532288,0.0,30585.41286110878,14783664.0,0,0,sparse,0.916647564469914
> pyanns,pyanns_qdrop0.1_ef70,sparse-full,10,7304.167282910146,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9198710601719198
> pyanns,pyanns_qdrop0.08_ef70,sparse-full,10,6928.843598434278,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9218338108882522
> pyanns,pyanns_qdrop0.1_ef75,sparse-full,10,6986.467927685548,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9243409742120343
> pyanns,pyanns_qdrop0.08_ef75,sparse-full,10,6550.183558450218,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9270916905444126
> pyanns,pyanns_qdrop0.1_ef80,sparse-full,10,6641.110968200012,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9282521489971346
> pyanns,pyanns_qdrop0.08_ef80,sparse-full,10,6275.986771574277,0.0,30585.41286110878,14783664.0,0,0,sparse,0.9311174785100287
> ```
> 
> Please note that you can submit at most 10 search configurations, so please remove some search parameters (without adding new since the deadline has passed.)

Thanks! I'll remove some configs soon.

**Comment by veaaaab** [comment]
> Please remove search configurations.

I've removed some configs. Hope you can check it out. Thanks!

**Review by maumueller — APPROVED** [review]

**Comment by harsha-simhadri** [comment]
@veaaaab What is the CMT entry corresponding to this entry? You could reach out to me via email too if do not want to list here.

**Pull request merged**
