### PR TITLE
[NeurIPS 2023 OOD Track] FDUx2-mysteryann Submission

### PR DESCRIPTION
**Pull request by matchyc**
Team FDUx2 intends to submit multiple tracks under the name FDUx2-<algorithm-name>, and here is **FDUx2-mysteryann for OOD track**.

We would like to express our gratitude to the organizers for your patient evaluation.

### CODE REVIEW

**Comment by matchyc** [comment]
If the deadline is specified by UTC-7, I suppose we can also provide a variant with other parameters for better performance in another PR.

**Comment by harsha-simhadri** [comment]
@matchyc Thanks for the PR. These are the results I see. You are welcome to provide another set of params, but I will not be able to provide further feedback. I will just merge and run the final evaluation.

```
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 100, 'T': 8}))",text2image-10M,10,25972.7125466913,0.0,10054.136591434479,3442296.0,0,0,ood,0.8901859999999999
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 110, 'T': 8}))",text2image-10M,10,23960.960062191152,0.0,10054.136591434479,3442296.0,0,0,ood,0.8962920000000001
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 118, 'T': 8}))",text2image-10M,10,22555.24801714806,0.0,10054.136591434479,3442296.0,0,0,ood,0.9003249999999999
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 120, 'T': 8}))",text2image-10M,10,22190.251905649486,0.0,10054.136591434479,3442296.0,0,0,ood,0.901281
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 123, 'T': 8}))",text2image-10M,10,21777.656995713216,0.0,10054.136591434479,3442296.0,0,0,ood,0.9027369999999999
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 125, 'T': 8}))",text2image-10M,10,21416.5746247916,0.0,10054.136591434479,3442296.0,0,0,ood,0.903621
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 128, 'T': 8}))",text2image-10M,10,21042.52695508358,0.0,10054.136591434479,3442296.0,0,0,ood,0.9048
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 130, 'T': 8}))",text2image-10M,10,20714.551841495875,0.0,10054.136591434479,3442296.0,0,0,ood,0.905621
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 133, 'T': 8}))",text2image-10M,10,20260.53624892588,0.0,10054.136591434479,3442296.0,0,0,ood,0.906866
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 135, 'T': 8}))",text2image-10M,10,20056.785183920634,0.0,10054.136591434479,3442296.0,0,0,ood,0.9076739999999999
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 140, 'T': 8}))",text2image-10M,10,19398.64130552921,0.0,10054.136591434479,3442296.0,0,0,ood,0.909539
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 145, 'T': 8}))",text2image-10M,10,18814.805218527497,0.0,10054.136591434479,3442296.0,0,0,ood,0.9113239999999999
mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 150, 'T': 8}))",text2image-10M,10,18306.685375319208,0.0,10054.136591434479,3442296.0,0,0,ood,0.912903
```

**Comment by matchyc** [comment]
> @matchyc Thanks for the PR. These are the results I see. You are welcome to provide another set of params, but I will not be able to provide further feedback. I will just merge and run the final evaluation.
> 
> ```
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 100, 'T': 8}))",text2image-10M,10,25972.7125466913,0.0,10054.136591434479,3442296.0,0,0,ood,0.8901859999999999
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 110, 'T': 8}))",text2image-10M,10,23960.960062191152,0.0,10054.136591434479,3442296.0,0,0,ood,0.8962920000000001
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 118, 'T': 8}))",text2image-10M,10,22555.24801714806,0.0,10054.136591434479,3442296.0,0,0,ood,0.9003249999999999
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 120, 'T': 8}))",text2image-10M,10,22190.251905649486,0.0,10054.136591434479,3442296.0,0,0,ood,0.901281
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 123, 'T': 8}))",text2image-10M,10,21777.656995713216,0.0,10054.136591434479,3442296.0,0,0,ood,0.9027369999999999
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 125, 'T': 8}))",text2image-10M,10,21416.5746247916,0.0,10054.136591434479,3442296.0,0,0,ood,0.903621
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 128, 'T': 8}))",text2image-10M,10,21042.52695508358,0.0,10054.136591434479,3442296.0,0,0,ood,0.9048
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 130, 'T': 8}))",text2image-10M,10,20714.551841495875,0.0,10054.136591434479,3442296.0,0,0,ood,0.905621
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 133, 'T': 8}))",text2image-10M,10,20260.53624892588,0.0,10054.136591434479,3442296.0,0,0,ood,0.906866
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 135, 'T': 8}))",text2image-10M,10,20056.785183920634,0.0,10054.136591434479,3442296.0,0,0,ood,0.9076739999999999
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 140, 'T': 8}))",text2image-10M,10,19398.64130552921,0.0,10054.136591434479,3442296.0,0,0,ood,0.909539
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 145, 'T': 8}))",text2image-10M,10,18814.805218527497,0.0,10054.136591434479,3442296.0,0,0,ood,0.9113239999999999
> mysteryann,"mystery_order_sq8(('M_bp35_L_pq500_NoT5_ord', {'L_pq': 150, 'T': 8}))",text2image-10M,10,18306.685375319208,0.0,10054.136591434479,3442296.0,0,0,ood,0.912903
> ```

Thanks for your comments, it is OK to merge and if the commit you have evaluated works, just use the commit in this feedback version, thank you.

**Comment by harsha-simhadri** [comment]
@matchyc  What is the CMT entry corresponding to this entry? You could reach out to me via email too if do not want to list here.

**Comment by matchyc** [comment]
> @matchyc What is the CMT entry corresponding to this entry? You could reach out to me via email too if do not want to list here.

Thank you for your reminder! 
Conference Name: Practical Vector Search Challenge: NeurIPS 2023 Competition track
Paper ID: 15
Paper Title: Fast OOD-ANN

**Pull request merged**
