### PR TITLE
WM_filter team  submission for Neurips23 Filter track

### PR DESCRIPTION
**Pull request by alemagnani**
WM_filter  submission by the WM_filter team

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
@alemagnani  Thanks for the PR. I see the following results. If they are as you expected, I will merge the PR

```
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 80, 'max_codes': 1800, 'selector_probe_limit': 80}))",yfcc-10M,10,14018.102428739292,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.8865040000000001
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 70, 'max_codes': 2100, 'selector_probe_limit': 70}))",yfcc-10M,10,14211.367280430806,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.887204
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 100, 'max_codes': 1800, 'selector_probe_limit': 100}))",yfcc-10M,10,14353.674433458516,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.897899
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 120, 'max_codes': 1800, 'selector_probe_limit': 120}))",yfcc-10M,10,14183.507967094347,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.90434
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 100, 'max_codes': 2100, 'selector_probe_limit': 100}))",yfcc-10M,10,14202.459502136597,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.906396
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 140, 'max_codes': 1800, 'selector_probe_limit': 140}))",yfcc-10M,10,14327.977731686831,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.908275
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 160, 'max_codes': 1800, 'selector_probe_limit': 160}))",yfcc-10M,10,14198.269094433073,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.910918
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 130, 'max_codes': 2100, 'selector_probe_limit': 130}))",yfcc-10M,10,14156.079683299406,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.915053
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 160, 'max_codes': 2100, 'selector_probe_limit': 160}))",yfcc-10M,10,14246.556805165725,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.91951
wm_filter,"Faiss(('IVF1024,SQ8', 'direct', {'nprobe': 200, 'max_codes': 2100, 'selector_probe_limit': 200}))",yfcc-10M,10,14156.497273536086,0.0,753.1679794788361,6296004.0,0.0,0.0,filter,0.9222340000000001
```

**Comment by alemagnani** [comment]
thanks for running this.
I haven't had a chance to run the code on the exact server but these
numbers are in line with the closest server I could get. The numbers are
actually slightly faster but more flat across the configurations.
I had some trouble deciding what configuration to submit because on
different servers I get very different index configurations as optimal.
Later would it be possible to submit a different configuration again to try
before the deadline?
Will you post these on a leaderboard?

thanks again
Alessandro

**Comment by harsha-simhadri** [comment]
Let me merge this PR for now. If you send another set of params before Oct 31, I will include them in the final evaluation.

**Comment by harsha-simhadri** [comment]
@alemagnani This docker takes extremely long to build since you seem to be compiling a lot of components from source. Could you consider enabling multi-threaded compilation using "make -j" if it is not enabled already?

**Comment by alemagnani** [comment]
On my vm cmake compilation multithreaded fails for some strange reason. The
multithreaded compilation is enabled for Faiss already.

**Comment by alemagnani** [comment]
The problem is that Faiss depends on a pretty recent version of cmake and
the base docker image doesn’t have that available. I apologize for any
inconvenience
Alessandro

**Comment by harsha-simhadri** [comment]
ok, no problem. lets keep things as is. if you figure out later how to make it multithreaded, please update.

**Comment by alemagnani** [comment]
Dear Harsha,
I had a peek at the results for the filter track and I saw that our team is
4th. Is there still a chance that we will be presenting? I am asking
because an invitation to speak would make it possible for my travel to be
approved otherwise i might not be able to attend. If you could let us know
as soon as you can of the final decision i would greatly appreciate it.

thanks
Alessandro

**Comment by mdouze** [comment]
Hi @alemagnani 
I'm sorry, only one team per track is invited... 
I am preparing a few summary slides for the bigann challenge for the neurips track on Sat 16th.
Would you mind summarizing how your indexing works? Or otherwise send me slides, any info is welcome. 
Thanks!

**Comment by alemagnani** [comment]
Thanks Matthijs,
I included a small presentation about it.
Thanks again for organizing this. I am looking forward to the writeup about
it.

A few more comments/questions:

   - I think it would have been better not to have vectors with int_8
   entries. That opened the possibility of optimizing speed based on the int8
   even though it had nothing to do with filtering
   - Would you be interested in a cleanup PR on this solution to add more
   filtering capabilities to Faiss?

thanks
Alessandro

**Comment by mdouze** [comment]
Thanks, where is the small presentation?

**Comment by alemagnani** [comment]
it was attached to the email i can see it but let me add it again.

**Comment by mdouze** [comment]
I don't think attachements get posted on the PR. Could you send it directly to matthijs@meta.com ?

**Pull request merged**
