### PR TITLE
[NeurIPS 2023 OOD Track] Puck

### PR DESCRIPTION
**Pull request by nk2014yj**
Puck participated in the OOD track. This is the code for Puck. Thank you.

### CODE REVIEW

**Comment by harsha-simhadri** [comment]
Did you intend to submit two entries to the OOD track?

**Comment by nk2014yj** [comment]
Yes. 
The difference between puck-fizz and puck is that puck-fizz uses the published query dataset during the indexing stage.

**Comment by harsha-simhadri** [comment]
@nk2014yj  thanks for the PR. Does this agree with your experiments

```
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 160})",text2image-10M,10,8861.585558682262,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9015829999999999
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 165})",text2image-10M,10,8635.750395405932,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9040100000000001
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 170})",text2image-10M,10,8423.64192677345,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9061980000000001
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 175})",text2image-10M,10,8312.184281522512,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9083629999999999
puck,"Puck('C1000_F1000_Neighborhood16_Construction200', {'search_coarse_count': 10, 'tinker_search_range': 190})",text2image-10M,10,7772.49002208958,0.0,3725.2352855205536,10215024.0,0.0,0.0,ood,0.9141640000000001
```

**Comment by nk2014yj** [comment]
Yes, agrees with our experimental results. Thanks

**Pull request merged**
