### PR TITLE
[NeurIPS 2023 Sparse Track] FDUx2-shnsw Submission

### PR DESCRIPTION
**Pull request by matchyc**
Team FDUx2 intends to submit multiple tracks under the name FDUx2-\<algorithm-name\>, and here is **FDUx2-shnsw for Sparse Track**.
We would like to express our gratitude to the organizers for your patient evaluation.

### CODE REVIEW

**Review by ingberam — APPROVED** [review]
LGTM, code builds and runs on a VM with 8cpu/16GB memory (GCP `n2-custom-8-16384`).

@matchyc: please approve that these results are roughly what you would expect? 


```
shnsw,sparse_hnswlib,sparse-full,10,12177.737054397963,0.0,29630.818413734436,11034980.0,0,0,sparse,0.7994269340974212
shnsw,sparse_hnswlib,sparse-full,10,7947.033044411104,0.0,29630.818413734436,11034980.0,0,0,sparse,0.8854297994269341
shnsw,sparse_hnswlib,sparse-full,10,7367.327526288479,0.0,29630.818413734436,11034980.0,0,0,sparse,0.8951002865329514
shnsw,sparse_hnswlib,sparse-full,10,7048.045510025735,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9010458452722062
shnsw,sparse_hnswlib,sparse-full,10,6848.650637956033,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9048137535816618
shnsw,sparse_hnswlib,sparse-full,10,6667.224295496154,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9072206303724929
shnsw,sparse_hnswlib,sparse-full,10,6394.325862427465,0.0,29630.818413734436,11034980.0,0,0,sparse,0.911404011461318
shnsw,sparse_hnswlib,sparse-full,10,6247.696169337714,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9134527220630373
shnsw,sparse_hnswlib,sparse-full,10,5375.535588116485,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9266189111747851
shnsw,sparse_hnswlib,sparse-full,10,5106.970919323923,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9309312320916906
shnsw,sparse_hnswlib,sparse-full,10,4847.612098861592,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9353008595988539
shnsw,sparse_hnswlib,sparse-full,10,4642.8395496375015,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9382091690544412
shnsw,sparse_hnswlib,sparse-full,10,4442.987157238651,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9417335243553009
```

**Comment by matchyc** [comment]
> LGTM, code builds and runs on a VM with 8cpu/16GB memory (GCP `n2-custom-8-16384`).
> 
> @matchyc: please approve that these results are roughly what you would expect?
> 
> ```
> shnsw,sparse_hnswlib,sparse-full,10,12177.737054397963,0.0,29630.818413734436,11034980.0,0,0,sparse,0.7994269340974212
> shnsw,sparse_hnswlib,sparse-full,10,7947.033044411104,0.0,29630.818413734436,11034980.0,0,0,sparse,0.8854297994269341
> shnsw,sparse_hnswlib,sparse-full,10,7367.327526288479,0.0,29630.818413734436,11034980.0,0,0,sparse,0.8951002865329514
> shnsw,sparse_hnswlib,sparse-full,10,7048.045510025735,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9010458452722062
> shnsw,sparse_hnswlib,sparse-full,10,6848.650637956033,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9048137535816618
> shnsw,sparse_hnswlib,sparse-full,10,6667.224295496154,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9072206303724929
> shnsw,sparse_hnswlib,sparse-full,10,6394.325862427465,0.0,29630.818413734436,11034980.0,0,0,sparse,0.911404011461318
> shnsw,sparse_hnswlib,sparse-full,10,6247.696169337714,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9134527220630373
> shnsw,sparse_hnswlib,sparse-full,10,5375.535588116485,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9266189111747851
> shnsw,sparse_hnswlib,sparse-full,10,5106.970919323923,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9309312320916906
> shnsw,sparse_hnswlib,sparse-full,10,4847.612098861592,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9353008595988539
> shnsw,sparse_hnswlib,sparse-full,10,4642.8395496375015,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9382091690544412
> shnsw,sparse_hnswlib,sparse-full,10,4442.987157238651,0.0,29630.818413734436,11034980.0,0,0,sparse,0.9417335243553009
> ```

The results match our observation, thank you for your feed back.

**Comment by Leslie-Chung** [comment]
@ingberam Hi! We see that some people are still submitting, if it is still possible to change the parameters please let me know!

**Comment by matchyc** [comment]
@harsha-simhadri   Same entry from one team, thank you for your reminder!

Conference Name: Practical Vector Search Challenge: NeurIPS 2023 Competition track
Paper ID: 15
Paper Title: Fast OOD-ANN

**Pull request merged**
